import type { Level, Token } from "./types";
import { sentencesB2, sentencesC1, sentencesC2, talesB2, talesC1, talesC2 } from "./upper";

function line(pairs: [string, string][]): Token[] {
  const tokens: Token[] = pairs.map(([en, th]) => ({ en, th }));
  const last = tokens[tokens.length - 1];
  if (last) last.sentenceEnd = true;
  return tokens;
}

/** A1 sentences. Each Thai gloss follows that English word in context. */
export const sentences: Token[][] = [
  line([
    ["I", "ฉัน"],
    ["go", "ไป"],
    ["to", "ที่"],
    ["school", "โรงเรียน"],
    ["every", "ทุก"],
    ["morning", "เช้า"],
  ]),
  line([
    ["She", "เธอ"],
    ["drinks", "ดื่ม"],
    ["milk", "นม"],
    ["before", "ก่อน"],
    ["she", "เธอ"],
    ["sleeps", "หลับ"],
  ]),
  line([
    ["We", "เรา"],
    ["eat", "กิน"],
    ["rice", "ข้าว"],
    ["with", "กับ"],
    ["soup", "ซุป"],
    ["at", "ที่"],
    ["home", "บ้าน"],
  ]),
  line([
    ["He", "เขา"],
    ["walks", "เดิน"],
    ["to", "ไป"],
    ["the", "ที่"],
    ["market", "ตลาด"],
    ["after", "หลัง"],
    ["work", "เลิกงาน"],
  ]),
  line([
    ["My", "ของฉัน"],
    ["sister", "พี่สาว"],
    ["reads", "อ่าน"],
    ["a", "หนึ่งเล่ม"],
    ["book", "หนังสือ"],
    ["every", "ทุก"],
    ["night", "คืน"],
  ]),
  line([
    ["They", "พวกเขา"],
    ["play", "เล่น"],
    ["football", "ฟุตบอล"],
    ["in", "ใน"],
    ["the", "นั้น"],
    ["park", "สวน"],
    ["today", "วันนี้"],
  ]),
  line([
    ["I", "ฉัน"],
    ["want", "อยาก"],
    ["to", "จะ"],
    ["buy", "ซื้อ"],
    ["fresh", "สด"],
    ["fruit", "ผลไม้"],
    ["today", "วันนี้"],
  ]),
  line([
    ["Please", "โปรด"],
    ["open", "เปิด"],
    ["the", "นั้น"],
    ["window", "หน้าต่าง"],
    ["for", "ให้"],
    ["me", "ฉัน"],
    ["now", "เดี๋ยวนี้"],
  ]),
  line([
    ["The", "นั้น"],
    ["children", "เด็กๆ"],
    ["are", "กำลัง"],
    ["happy", "มีความสุข"],
    ["at", "ที่"],
    ["school", "โรงเรียน"],
    ["today", "วันนี้"],
  ]),
  line([
    ["Please", "โปรด"],
    ["give", "ให้"],
    ["me", "ฉัน"],
    ["a", "หนึ่ง"],
    ["cup", "ถ้วย"],
    ["of", "ของ"],
    ["water", "น้ำ"],
  ]),
  line([
    ["I", "ฉัน"],
    ["brush", "แปรง"],
    ["my", "ของฉัน"],
    ["teeth", "ฟัน"],
    ["every", "ทุก"],
    ["morning", "เช้า"],
  ]),
  line([
    ["She", "เธอ"],
    ["is", "เป็น"],
    ["a", "คนหนึ่ง"],
    ["teacher", "ครู"],
    ["at", "ที่"],
    ["my", "ของฉัน"],
    ["school", "โรงเรียน"],
  ]),
  line([
    ["We", "เรา"],
    ["go", "ไป"],
    ["to", "ที่"],
    ["the", "นั้น"],
    ["shop", "ร้าน"],
    ["on", "ใน"],
    ["Sunday", "วันอาทิตย์"],
  ]),
  line([
    ["He", "เขา"],
    ["never", "ไม่เคย"],
    ["likes", "ชอบ"],
    ["cold", "หนาว"],
    ["weather", "อากาศ"],
    ["here", "ที่นี่"],
  ]),
  line([
    ["There", "มี"],
    ["is", "อยู่"],
    ["a", "หนึ่ง"],
    ["cat", "แมว"],
    ["under", "ใต้"],
    ["the", "นั้น"],
    ["table", "โต๊ะ"],
  ]),
  line([
    ["I", "ฉัน"],
    ["take", "นั่ง"],
    ["the", "นั้น"],
    ["bus", "รถเมล์"],
    ["to", "ไป"],
    ["work", "ทำงาน"],
    ["every", "ทุก"],
    ["day", "วัน"],
  ]),
  line([
    ["Her", "ของเธอ"],
    ["father", "พ่อ"],
    ["works", "ทำงาน"],
    ["in", "ใน"],
    ["a", "หนึ่ง"],
    ["small", "เล็ก"],
    ["office", "สำนักงาน"],
  ]),
  line([
    ["I", "ฉัน"],
    ["am", "กำลัง"],
    ["learning", "เรียน"],
    ["English", "ภาษาอังกฤษ"],
    ["with", "กับ"],
    ["my", "ของฉัน"],
    ["friend", "เพื่อน"],
  ]),
  line([
    ["Do", "ไหม"],
    ["you", "คุณ"],
    ["want", "อยาก"],
    ["to", "จะ"],
    ["eat", "กิน"],
    ["lunch", "อาหารเที่ยง"],
    ["now", "ตอนนี้"],
  ]),
  line([
    ["The", "นั้น"],
    ["sky", "ท้องฟ้า"],
    ["is", "เป็น"],
    ["blue", "สีฟ้า"],
    ["and", "และ"],
    ["very", "มาก"],
    ["bright", "สว่าง"],
  ]),
  line([
    ["Please", "โปรด"],
    ["sit", "นั่ง"],
    ["down", "ลง"],
    ["and", "และ"],
    ["open", "เปิด"],
    ["your", "ของคุณ"],
    ["book", "หนังสือ"],
  ]),
  line([
    ["We", "เรา"],
    ["have", "มี"],
    ["two", "สอง"],
    ["cats", "แมว"],
    ["and", "และ"],
    ["one", "หนึ่ง"],
    ["dog", "สุนัข"],
  ]),
  line([
    ["She", "เธอ"],
    ["walks", "เดิน"],
    ["home", "กลับบ้าน"],
    ["after", "หลังจาก"],
    ["class", "ชั้นเรียน"],
    ["ends", "จบ"],
  ]),
  line([
    ["I", "ฉัน"],
    ["need", "ต้องการ"],
    ["a", "หนึ่ง"],
    ["pen", "ปากกา"],
    ["and", "และ"],
    ["some", "บางส่วน"],
    ["paper", "กระดาษ"],
  ]),
  line([
    ["He", "เขา"],
    ["gets", "ตื่น"],
    ["up", "ขึ้น"],
    ["early", "แต่เช้า"],
    ["and", "และ"],
    ["drinks", "ดื่ม"],
    ["coffee", "กาแฟ"],
  ]),
  line([
    ["My", "ของฉัน"],
    ["friends", "เพื่อน"],
    ["and", "และ"],
    ["I", "ฉัน"],
    ["study", "เรียน"],
    ["after", "หลัง"],
    ["dinner", "มื้อเย็น"],
  ]),
  line([
    ["It", "อากาศ"],
    ["is", "เป็น"],
    ["cold", "หนาว"],
    ["so", "ดังนั้น"],
    ["I", "ฉัน"],
    ["wear", "สวม"],
    ["a", "หนึ่ง"],
    ["coat", "เสื้อโค้ท"],
  ]),
  line([
    ["Can", "ได้ไหม"],
    ["we", "เรา"],
    ["meet", "พบ"],
    ["at", "ที่"],
    ["the", "นั้น"],
    ["station", "สถานี"],
    ["at", "ตอน"],
    ["noon", "เที่ยง"],
  ]),
  line([
    ["I", "ฉัน"],
    ["like", "ชอบ"],
    ["to", "ที่จะ"],
    ["listen", "ฟัง"],
    ["to", "ถึง"],
    ["music", "เพลง"],
    ["at", "ตอน"],
    ["night", "กลางคืน"],
  ]),
  line([
    ["This", "นี้"],
    ["bag", "กระเป๋า"],
    ["is", "เป็น"],
    ["too", "เกินไป"],
    ["heavy", "หนัก"],
    ["for", "สำหรับ"],
    ["me", "ฉัน"],
  ]),
  line([
    ["I", "ฉัน"],
    ["don't", "ไม่"],
    ["like", "ชอบ"],
    ["very", "มาก"],
    ["sweet", "หวาน"],
    ["coffee", "กาแฟ"],
  ]),
  line([
    ["I'm", "ฉัน"],
    ["ready", "พร้อม"],
    ["to", "ที่จะ"],
    ["go", "ไป"],
    ["to", "ที่"],
    ["school", "โรงเรียน"],
    ["now", "ตอนนี้"],
  ]),
];

function story(title: string, lines: [string, string][][], scenes: string[]): Token[][] {
  if (scenes.length !== lines.length) {
    throw new Error(`${title}: ${scenes.length} scenes for ${lines.length} lines`);
  }
  return lines.map((pairs, index) => {
    const tokens = line(pairs);
    for (const token of tokens) {
      token.tale = title;
      token.scene = scenes[index];
    }
    return tokens;
  });
}

/** Short A1 tales, kept in reading order. */
export const tales: Token[][] = [
  ...story("สิงโตกับหนู", [
    [
      ["A", "ตัว"],
      ["big", "ใหญ่"],
      ["lion", "สิงโต"],
      ["sleeps", "หลับ"],
      ["under", "ใต้"],
      ["a", "ต้น"],
      ["tall", "สูง"],
      ["tree", "ไม้"],
    ],
    [
      ["A", "ตัว"],
      ["small", "เล็ก"],
      ["mouse", "หนู"],
      ["runs", "วิ่ง"],
      ["across", "ผ่าน"],
      ["his", "ของเขา"],
      ["big", "ใหญ่"],
      ["paw", "อุ้งเท้า"],
    ],
    [
      ["The", "ตัว"],
      ["lion", "สิงโต"],
      ["wakes", "ตื่น"],
      ["and", "แล้ว"],
      ["catches", "จับ"],
      ["the", "ตัว"],
      ["little", "เล็ก"],
      ["mouse", "หนู"],
    ],
    [
      ["Please", "โปรด"],
      ["let", "ปล่อย"],
      ["me", "ฉัน"],
      ["go", "ไป"],
      ["says", "พูด"],
      ["the", "ตัว"],
      ["little", "เล็ก"],
      ["mouse", "หนู"],
    ],
    [
      ["The", "ตัว"],
      ["kind", "ใจดี"],
      ["lion", "สิงโต"],
      ["smiles", "ยิ้ม"],
      ["and", "แล้ว"],
      ["lets", "ปล่อย"],
      ["the", "ตัว"],
      ["mouse", "หนู"],
      ["go", "ไป"],
    ],
    [
      ["Some", "พวก"],
      ["hunters", "พราน"],
      ["catch", "จับ"],
      ["the", "ตัว"],
      ["lion", "สิงโต"],
      ["in", "ด้วย"],
      ["a", "ผืน"],
      ["strong", "แข็งแรง"],
      ["net", "ตาข่าย"],
    ],
    [
      ["The", "ตัว"],
      ["mouse", "หนู"],
      ["hears", "ได้ยิน"],
      ["him", "เขา"],
      ["and", "แล้ว"],
      ["runs", "วิ่ง"],
      ["back", "กลับ"],
      ["to", "ไป"],
      ["help", "ช่วย"],
    ],
    [
      ["She", "เธอ"],
      ["bites", "กัด"],
      ["the", "ผืน"],
      ["net", "ตาข่าย"],
      ["until", "จน"],
      ["the", "ตัว"],
      ["lion", "สิงโต"],
      ["is", "เป็น"],
      ["free", "อิสระ"],
    ],
    [
      ["Thank", "ขอบคุณ"],
      ["you", "เธอ"],
      ["my", "ของฉัน"],
      ["little", "เล็ก"],
      ["friend", "เพื่อน"],
      ["says", "พูด"],
      ["the", "ตัว"],
      ["happy", "ดีใจ"],
      ["lion", "สิงโต"],
    ],
  ], [
    "lion-sleep",
    "lion-paw",
    "lion-catch",
    "lion-please",
    "lion-lets",
    "lion-net",
    "lion-runs",
    "lion-bites",
    "lion-thanks",
  ]),
  ...story("เต่ากับกระต่าย", [
    [
      ["A", "ตัว"],
      ["fast", "เร็ว"],
      ["hare", "กระต่าย"],
      ["laughs", "หัวเราะ"],
      ["at", "ใส่"],
      ["a", "ตัว"],
      ["slow", "ช้า"],
      ["tortoise", "เต่า"],
    ],
    [
      ["Let", "มา"],
      ["us", "กัน"],
      ["race", "แข่ง"],
      ["to", "ไป"],
      ["that", "ต้น"],
      ["big", "ใหญ่"],
      ["tree", "ไม้"],
      ["says", "พูด"],
      ["the", "ตัว"],
      ["hare", "กระต่าย"],
    ],
    [
      ["The", "ตัว"],
      ["hare", "กระต่าย"],
      ["runs", "วิ่ง"],
      ["far", "ไกล"],
      ["ahead", "นำหน้า"],
      ["and", "แล้ว"],
      ["stops", "หยุด"],
      ["to", "เพื่อ"],
      ["rest", "พัก"],
    ],
    [
      ["He", "เขา"],
      ["sleeps", "หลับ"],
      ["under", "ใต้"],
      ["a", "ต้น"],
      ["tree", "ไม้"],
      ["beside", "ข้าง"],
      ["the", "เส้น"],
      ["long", "ยาว"],
      ["road", "ทาง"],
    ],
    [
      ["The", "ตัว"],
      ["slow", "ช้า"],
      ["tortoise", "เต่า"],
      ["keeps", "ยัง"],
      ["walking", "เดินต่อ"],
      ["and", "และ"],
      ["does", "ไม่"],
      ["not", "ได้"],
      ["stop", "หยุด"],
    ],
    [
      ["She", "เธอ"],
      ["passes", "ผ่าน"],
      ["the", "ตัว"],
      ["sleeping", "ที่หลับ"],
      ["hare", "กระต่าย"],
      ["and", "แล้ว"],
      ["walks", "เดิน"],
      ["to", "ถึง"],
      ["the", "ต้น"],
      ["tree", "ไม้"],
    ],
    [
      ["The", "ตัว"],
      ["hare", "กระต่าย"],
      ["wakes", "ตื่น"],
      ["and", "แล้ว"],
      ["runs", "วิ่ง"],
      ["but", "แต่"],
      ["he", "เขา"],
      ["is", "มา"],
      ["too", "สาย"],
      ["late", "เกิน"],
    ],
    [
      ["Slow", "ช้า"],
      ["and", "และ"],
      ["steady", "มั่นคง"],
      ["wins", "ชนะ"],
      ["the", "การ"],
      ["race", "แข่ง"],
      ["that", "วัน"],
      ["sunny", "แจ่มใส"],
      ["day", "นั้น"],
    ],
  ], [
    "hare-laugh",
    "hare-start",
    "hare-ahead",
    "hare-sleep",
    "tortoise-walk",
    "tortoise-pass",
    "hare-late",
    "tortoise-win",
  ]),
  ...story("เด็กหญิงผ้าคลุมแดง", [
    [
      ["A", "เด็ก"],
      ["girl", "หญิง"],
      ["in", "ใส่"],
      ["a", "ผ้า"],
      ["red", "แดง"],
      ["cloak", "คลุม"],
      ["walks", "เดิน"],
      ["to", "ไปหา"],
      ["Grandma", "คุณย่า"],
    ],
    [
      ["She", "เธอ"],
      ["carries", "ถือ"],
      ["cake", "เค้ก"],
      ["and", "กับ"],
      ["fresh", "สด"],
      ["fruit", "ผลไม้"],
      ["in", "ใน"],
      ["her", "ของเธอ"],
      ["basket", "ตะกร้า"],
    ],
    [
      ["A", "ตัว"],
      ["hungry", "หิว"],
      ["wolf", "หมาป่า"],
      ["stops", "หยุด"],
      ["her", "เธอ"],
      ["on", "บน"],
      ["the", "เส้น"],
      ["forest", "ป่า"],
      ["path", "ทางเดิน"],
    ],
    [
      ["Where", "ที่ไหน"],
      ["are", "กำลัง"],
      ["you", "เธอ"],
      ["going", "ไป"],
      ["today", "วันนี้"],
      ["little", "น้อย"],
      ["girl", "หนู"],
      ["asks", "ถาม"],
      ["the", "ตัว"],
      ["wolf", "หมาป่า"],
    ],
    [
      ["I", "ฉัน"],
      ["am", "กำลัง"],
      ["going", "ไป"],
      ["to", "หา"],
      ["my", "ของฉัน"],
      ["sick", "ไม่สบาย"],
      ["Grandma", "คุณย่า"],
      ["says", "พูด"],
      ["the", "เด็ก"],
      ["girl", "หญิง"],
    ],
    [
      ["The", "ตัว"],
      ["wolf", "หมาป่า"],
      ["runs", "วิ่ง"],
      ["to", "ไป"],
      ["the", "บ้าน"],
      ["house", "นั้น"],
      ["before", "ก่อน"],
      ["the", "เด็ก"],
      ["little", "น้อย"],
      ["girl", "หนู"],
    ],
    [
      ["He", "เขา"],
      ["puts", "สวม"],
      ["on", "ไว้"],
      ["her", "ของย่า"],
      ["cap", "หมวก"],
      ["and", "แล้ว"],
      ["lies", "นอน"],
      ["in", "บน"],
      ["the", "เตียง"],
      ["bed", "นั้น"],
    ],
    [
      ["What", "ช่าง"],
      ["big", "ใหญ่"],
      ["eyes", "ตา"],
      ["you", "เธอ"],
      ["have", "มี"],
      ["says", "พูด"],
      ["the", "เด็ก"],
      ["brave", "กล้า"],
      ["girl", "หญิง"],
    ],
    [
      ["A", "คน"],
      ["hunter", "พราน"],
      ["hears", "ได้ยิน"],
      ["her", "เธอ"],
      ["and", "แล้ว"],
      ["sends", "ไล่"],
      ["the", "ตัว"],
      ["wolf", "หมาป่า"],
      ["away", "ออกไป"],
    ],
  ], [
    "red-walk",
    "red-basket",
    "red-stop",
    "red-ask",
    "red-answer",
    "wolf-house",
    "wolf-bed",
    "red-eyes",
    "hunter",
  ]),
];

/** A2 sentences. Past time, comparison, and slightly longer everyday words. */
export const sentencesA2: Token[][] = [
  line([
    ["I", "ฉัน"],
    ["visited", "ไปเยี่ยม"],
    ["my", "ของฉัน"],
    ["aunt", "คุณป้า"],
    ["last", "เมื่อ"],
    ["Sunday", "วันอาทิตย์"],
    ["morning", "เช้า"],
  ]),
  line([
    ["She", "เธอ"],
    ["usually", "มัก"],
    ["takes", "นั่ง"],
    ["the", "ขบวน"],
    ["train", "รถไฟ"],
    ["to", "ไป"],
    ["work", "ทำงาน"],
  ]),
  line([
    ["We", "เรา"],
    ["cooked", "ทำ"],
    ["dinner", "อาหารเย็น"],
    ["together", "ด้วยกัน"],
    ["because", "เพราะ"],
    ["Mom", "แม่"],
    ["was", "รู้สึก"],
    ["tired", "เหนื่อย"],
  ]),
  line([
    ["He", "เขา"],
    ["left", "ลืม"],
    ["his", "ของเขา"],
    ["bag", "กระเป๋า"],
    ["on", "บน"],
    ["the", "ขบวน"],
    ["morning", "เช้า"],
    ["train", "รถไฟ"],
  ]),
  line([
    ["They", "พวกเขา"],
    ["played", "เล่น"],
    ["football", "ฟุตบอล"],
    ["after", "หลัง"],
    ["school", "เลิกเรียน"],
    ["yesterday", "เมื่อวาน"],
  ]),
  line([
    ["I", "ฉัน"],
    ["am", "ตัว"],
    ["taller", "สูง"],
    ["than", "กว่า"],
    ["my", "ของฉัน"],
    ["younger", "น้อง"],
    ["brother", "ชาย"],
  ]),
  line([
    ["We", "เรา"],
    ["need", "ต้องการ"],
    ["more", "เพิ่ม"],
    ["time", "เวลา"],
    ["to", "เพื่อ"],
    ["finish", "ทำให้จบ"],
    ["this", "ชิ้นนี้"],
    ["homework", "การบ้าน"],
  ]),
  line([
    ["She", "เธอ"],
    ["bought", "ซื้อ"],
    ["a", "ใบ"],
    ["cheaper", "ถูกกว่า"],
    ["ticket", "ตั๋ว"],
    ["at", "ที่"],
    ["the", "แห่ง"],
    ["station", "สถานี"],
  ]),
  line([
    ["Did", "ไหม"],
    ["you", "คุณ"],
    ["enjoy", "สนุกกับ"],
    ["the", "เรื่อง"],
    ["film", "หนัง"],
    ["last", "เมื่อ"],
    ["night", "คืนที่แล้ว"],
  ]),
  line([
    ["I", "ฉัน"],
    ["sometimes", "บางครั้ง"],
    ["forget", "ลืม"],
    ["new", "ใหม่"],
    ["words", "คำศัพท์"],
    ["after", "หลัง"],
    ["class", "เลิกเรียน"],
  ]),
  line([
    ["My", "ของฉัน"],
    ["brother", "พี่ชาย"],
    ["wants", "อยาก"],
    ["to", "จะ"],
    ["become", "เป็น"],
    ["a", "คน"],
    ["doctor", "หมอ"],
  ]),
  line([
    ["The", "ร้าน"],
    ["shop", "นั้น"],
    ["was", "ได้"],
    ["closed", "ปิด"],
    ["when", "ตอนที่"],
    ["we", "เรา"],
    ["arrived", "ไปถึง"],
  ]),
  line([
    ["Please", "โปรด"],
    ["speak", "พูด"],
    ["more", "ให้"],
    ["slowly", "ช้าลง"],
    ["so", "จะได้"],
    ["I", "ฉัน"],
    ["understand", "เข้าใจ"],
  ]),
  line([
    ["We", "เรา"],
    ["walked", "เดิน"],
    ["through", "ผ่าน"],
    ["the", "สวน"],
    ["park", "นั้น"],
    ["after", "หลัง"],
    ["dinner", "มื้อเย็น"],
  ]),
  line([
    ["I", "ฉัน"],
    ["called", "โทรหา"],
    ["my", "ของฉัน"],
    ["friend", "เพื่อน"],
    ["because", "เพราะ"],
    ["I", "ฉัน"],
    ["was", "มา"],
    ["late", "สาย"],
  ]),
  line([
    ["She", "เธอ"],
    ["wears", "ใส่"],
    ["a", "ตัว"],
    ["warmer", "ที่อุ่นกว่า"],
    ["coat", "เสื้อโค้ท"],
    ["in", "ตอน"],
    ["winter", "ฤดูหนาว"],
  ]),
  line([
    ["They", "พวกเขา"],
    ["are", "กำลัง"],
    ["planning", "วางแผน"],
    ["a", "ทริป"],
    ["trip", "เที่ยว"],
    ["to", "ไป"],
    ["the", "ชาย"],
    ["beach", "หาด"],
  ]),
  line([
    ["Can", "ได้ไหม"],
    ["you", "คุณ"],
    ["help", "ช่วย"],
    ["me", "ฉัน"],
    ["carry", "ยก"],
    ["these", "พวก"],
    ["boxes", "กล่อง"],
  ]),
  line([
    ["I", "ฉัน"],
    ["felt", "รู้สึก"],
    ["tired", "เหนื่อย"],
    ["after", "หลัง"],
    ["the", "การ"],
    ["long", "ที่ยาว"],
    ["meeting", "ประชุม"],
  ]),
  line([
    ["Our", "ของเรา"],
    ["teacher", "ครู"],
    ["gave", "ให้"],
    ["us", "เรา"],
    ["an", "ชุด"],
    ["easy", "ง่าย"],
    ["test", "ข้อสอบ"],
  ]),
  line([
    ["We", "เรา"],
    ["should", "ควร"],
    ["leave", "ออก"],
    ["home", "จากบ้าน"],
    ["before", "ก่อน"],
    ["eight", "แปด"],
    ["o'clock", "โมง"],
  ]),
  line([
    ["I", "ฉัน"],
    ["prefer", "ชอบ"],
    ["tea", "ชา"],
    ["when", "เมื่อ"],
    ["the", "อากาศ"],
    ["weather", "นั้น"],
    ["is", "เป็น"],
    ["cold", "หนาว"],
  ]),
  line([
    ["She", "เธอ"],
    ["found", "เจอ"],
    ["her", "ของเธอ"],
    ["keys", "กุญแจ"],
    ["under", "ใต้"],
    ["the", "ตัว"],
    ["sofa", "โซฟา"],
  ]),
  line([
    ["He", "เขา"],
    ["studied", "อ่านหนังสือ"],
    ["harder", "หนักขึ้น"],
    ["than", "กว่า"],
    ["he", "เขา"],
    ["did", "ทำ"],
    ["last", "ปี"],
    ["year", "ที่แล้ว"],
  ]),
];

/** B1 sentences. Longer links, opinions, and less common words. */
export const sentencesB1: Token[][] = [
  line([
    ["I", "ฉัน"],
    ["have", "ได้"],
    ["lived", "อาศัย"],
    ["in", "ใน"],
    ["this", "ย่าน"],
    ["neighborhood", "นี้"],
    ["for", "มา"],
    ["years", "หลายปี"],
  ]),
  line([
    ["She", "เธอ"],
    ["decided", "ตัดสินใจ"],
    ["to", "จะ"],
    ["practice", "ฝึก"],
    ["English", "ภาษาอังกฤษ"],
    ["every", "ทุก"],
    ["evening", "เย็น"],
  ]),
  line([
    ["Although", "แม้"],
    ["it", "ฝน"],
    ["rained", "จะตก"],
    ["we", "เรา"],
    ["still", "ก็ยัง"],
    ["went", "ออกไป"],
    ["outside", "ข้างนอก"],
  ]),
  line([
    ["He", "เขา"],
    ["explained", "อธิบาย"],
    ["the", "ปัญหา"],
    ["problem", "นั้น"],
    ["until", "จน"],
    ["I", "ฉัน"],
    ["understood", "เข้าใจ"],
  ]),
  line([
    ["We", "เรา"],
    ["have", "ได้"],
    ["already", "ทำ"],
    ["finished", "เสร็จ"],
    ["most", "ส่วนใหญ่"],
    ["of", "ของ"],
    ["the", "ชิ้น"],
    ["project", "งาน"],
  ]),
  line([
    ["I", "ฉัน"],
    ["would", "อยาก"],
    ["rather", "จะ"],
    ["stay", "อยู่"],
    ["home", "บ้าน"],
    ["than", "มากกว่า"],
    ["travel", "ออกเดินทาง"],
    ["today", "วันนี้"],
  ]),
  line([
    ["The", "เล่ม"],
    ["book", "หนังสือ"],
    ["that", "ที่"],
    ["she", "เธอ"],
    ["lent", "ให้ยืม"],
    ["me", "ฉัน"],
    ["was", "มี"],
    ["useful", "ประโยชน์"],
  ]),
  line([
    ["They", "พวกเขา"],
    ["have", "ได้"],
    ["been", "เป็น"],
    ["friends", "เพื่อนกัน"],
    ["since", "ตั้งแต่"],
    ["primary", "ประถม"],
    ["school", "โรงเรียน"],
  ]),
  line([
    ["Please", "โปรด"],
    ["remind", "เตือน"],
    ["me", "ฉัน"],
    ["about", "เรื่อง"],
    ["the", "นัด"],
    ["afternoon", "ตอนบ่าย"],
    ["appointment", "หมาย"],
  ]),
  line([
    ["I", "ฉัน"],
    ["am", "กำลัง"],
    ["trying", "พยายาม"],
    ["to", "จะ"],
    ["improve", "พัฒนา"],
    ["my", "ของฉัน"],
    ["pronunciation", "การออกเสียง"],
  ]),
  line([
    ["If", "ถ้า"],
    ["you", "คุณ"],
    ["arrive", "มา"],
    ["early", "ก่อน"],
    ["we", "เรา"],
    ["can", "คุย"],
    ["talk", "กัน"],
    ["first", "ก่อนได้"],
  ]),
  line([
    ["She", "เธอ"],
    ["suggested", "แนะนำ"],
    ["a", "ร้าน"],
    ["quieter", "ที่เงียบกว่า"],
    ["cafe", "คาเฟ่"],
    ["near", "ใกล้"],
    ["the", "ที่"],
    ["office", "ทำงาน"],
  ]),
  line([
    ["He", "เขา"],
    ["did", "ไม่"],
    ["not", "ได้"],
    ["notice", "สังเกต"],
    ["the", "ข้อ"],
    ["mistake", "ผิด"],
    ["until", "จน"],
    ["later", "ภายหลัง"],
  ]),
  line([
    ["We", "เรา"],
    ["should", "ควร"],
    ["discuss", "คุย"],
    ["this", "แผน"],
    ["plan", "นี้"],
    ["before", "ก่อน"],
    ["Monday", "วันจันทร์"],
  ]),
  line([
    ["Learning", "การเรียน"],
    ["new", "คำ"],
    ["words", "ใหม่"],
    ["takes", "ต้องใช้"],
    ["time", "เวลา"],
    ["and", "กับ"],
    ["patience", "ความอดทน"],
  ]),
  line([
    ["I", "ฉัน"],
    ["have", "ไม่"],
    ["never", "เคย"],
    ["visited", "ไป"],
    ["that", "พิพิธภัณฑ์"],
    ["museum", "นั้น"],
    ["before", "มาก่อน"],
  ]),
  line([
    ["The", "ขบวน"],
    ["train", "รถไฟ"],
    ["was", "มา"],
    ["delayed", "สาย"],
    ["so", "เลย"],
    ["everyone", "ทุกคน"],
    ["waited", "รอ"],
  ]),
  line([
    ["She", "เธอ"],
    ["feels", "รู้สึก"],
    ["more", "มั่นใจ"],
    ["confident", "ขึ้น"],
    ["after", "หลัง"],
    ["daily", "ฝึก"],
    ["practice", "ทุกวัน"],
  ]),
  line([
    ["Could", "ได้ไหม"],
    ["you", "คุณ"],
    ["repeat", "พูด"],
    ["the", "ประโยค"],
    ["last", "สุดท้าย"],
    ["sentence", "อีกที"],
    ["please", "หน่อย"],
  ]),
  line([
    ["He", "เขา"],
    ["keeps", "เก็บ"],
    ["his", "ของเขา"],
    ["notes", "บันทึก"],
    ["in", "ใน"],
    ["a", "เล่ม"],
    ["small", "เล็ก"],
    ["notebook", "สมุด"],
  ]),
  line([
    ["We", "เรา"],
    ["agreed", "ตกลง"],
    ["to", "จะ"],
    ["meet", "เจอกัน"],
    ["after", "หลัง"],
    ["the", "คาบ"],
    ["evening", "เย็น"],
    ["class", "เรียน"],
  ]),
  line([
    ["I", "ฉัน"],
    ["finally", "ในที่สุด"],
    ["understood", "เข้าใจ"],
    ["the", "เรื่อง"],
    ["story", "นั้น"],
    ["on", "ใน"],
    ["that", "หน้า"],
    ["page", "นั้น"],
  ]),
  line([
    ["They", "พวกเขา"],
    ["usually", "มัก"],
    ["review", "ทบทวน"],
    ["mistakes", "ข้อผิด"],
    ["before", "ก่อน"],
    ["the", "การ"],
    ["test", "สอบ"],
  ]),
  line([
    ["A", "การ"],
    ["short", "สั้น"],
    ["walk", "เดิน"],
    ["often", "มัก"],
    ["helps", "ช่วย"],
    ["me", "ให้ฉัน"],
    ["think", "คิด"],
    ["clearly", "ได้ชัด"],
  ]),
];

const lionScenes = [
  "lion-sleep",
  "lion-paw",
  "lion-catch",
  "lion-please",
  "lion-lets",
  "lion-net",
  "lion-runs",
  "lion-bites",
  "lion-thanks",
];

const hareScenes = [
  "hare-laugh",
  "hare-start",
  "hare-ahead",
  "hare-sleep",
  "tortoise-walk",
  "tortoise-pass",
  "hare-late",
  "tortoise-win",
];

const redScenes = [
  "red-walk",
  "red-basket",
  "red-stop",
  "red-ask",
  "red-answer",
  "wolf-house",
  "wolf-bed",
  "red-eyes",
  "hunter",
];

/** Same three tales, told with A2 wording. Scenes stay in the same order. */
export const talesA2: Token[][] = [
  ...story("สิงโตกับหนู", [
    [
      ["A", "ตัว"],
      ["huge", "ใหญ่โต"],
      ["lion", "สิงโต"],
      ["slept", "หลับ"],
      ["under", "ใต้"],
      ["the", "ต้น"],
      ["shady", "ร่ม"],
      ["tree", "ไม้"],
    ],
    [
      ["A", "ตัว"],
      ["tiny", "จิ๋ว"],
      ["mouse", "หนู"],
      ["ran", "วิ่ง"],
      ["across", "ผ่าน"],
      ["his", "ของเขา"],
      ["heavy", "ที่หนัก"],
      ["paw", "อุ้งเท้า"],
    ],
    [
      ["The", "ตัว"],
      ["angry", "โกรธ"],
      ["lion", "สิงโต"],
      ["woke", "ตื่น"],
      ["and", "แล้ว"],
      ["caught", "จับ"],
      ["the", "ตัว"],
      ["mouse", "หนู"],
    ],
    [
      ["Please", "โปรด"],
      ["let", "ปล่อย"],
      ["me", "ฉัน"],
      ["go", "ไป"],
      ["and", "แล้ว"],
      ["I", "ฉัน"],
      ["will", "จะ"],
      ["help", "ช่วย"],
      ["you", "คุณ"],
    ],
    [
      ["The", "ตัว"],
      ["kind", "ใจดี"],
      ["lion", "สิงโต"],
      ["smiled", "ยิ้ม"],
      ["and", "แล้ว"],
      ["let", "ปล่อย"],
      ["him", "เขา"],
      ["leave", "ไป"],
    ],
    [
      ["Hunters", "พราน"],
      ["trapped", "ดัก"],
      ["the", "ตัว"],
      ["strong", "แข็งแรง"],
      ["lion", "สิงโต"],
      ["in", "ด้วย"],
      ["a", "ผืน"],
      ["net", "ตาข่าย"],
    ],
    [
      ["The", "ตัว"],
      ["mouse", "หนู"],
      ["heard", "ได้ยิน"],
      ["his", "ของเขา"],
      ["roar", "เสียงคำราม"],
      ["and", "แล้ว"],
      ["hurried", "รีบ"],
      ["back", "กลับมา"],
    ],
    [
      ["She", "เธอ"],
      ["chewed", "แทะ"],
      ["the", "เส้น"],
      ["ropes", "เชือก"],
      ["until", "จน"],
      ["he", "เขา"],
      ["was", "ได้"],
      ["free", "เป็นอิสระ"],
    ],
    [
      ["Thank", "ขอบคุณ"],
      ["you", "เจ้า"],
      ["little", "น้อย"],
      ["friend", "เพื่อน"],
      ["said", "พูด"],
      ["the", "ตัว"],
      ["grateful", "ที่ซาบซึ้ง"],
      ["lion", "สิงโต"],
    ],
  ], lionScenes),
  ...story("เต่ากับกระต่าย", [
    [
      ["A", "ตัว"],
      ["proud", "หยิ่ง"],
      ["hare", "กระต่าย"],
      ["laughed", "หัวเราะ"],
      ["at", "ใส่"],
      ["the", "ตัว"],
      ["slow", "ช้า"],
      ["tortoise", "เต่า"],
    ],
    [
      ["Let", "มา"],
      ["us", "กัน"],
      ["race", "แข่ง"],
      ["to", "ไป"],
      ["the", "ต้น"],
      ["far", "ที่ไกล"],
      ["tree", "ไม้"],
      ["he", "เขา"],
      ["said", "พูด"],
    ],
    [
      ["The", "ตัว"],
      ["hare", "กระต่าย"],
      ["ran", "วิ่ง"],
      ["ahead", "นำ"],
      ["and", "แล้ว"],
      ["stopped", "หยุด"],
      ["to", "เพื่อ"],
      ["rest", "พัก"],
    ],
    [
      ["He", "เขา"],
      ["fell", "หลับ"],
      ["asleep", "ไป"],
      ["beside", "ข้าง"],
      ["the", "เส้น"],
      ["quiet", "ที่เงียบ"],
      ["road", "ทาง"],
    ],
    [
      ["The", "ตัว"],
      ["tortoise", "เต่า"],
      ["kept", "ยัง"],
      ["walking", "เดิน"],
      ["and", "และ"],
      ["never", "ไม่"],
      ["stopped", "หยุดเลย"],
    ],
    [
      ["She", "เธอ"],
      ["passed", "ผ่าน"],
      ["the", "ตัว"],
      ["sleeping", "ที่หลับ"],
      ["hare", "กระต่าย"],
      ["near", "ใกล้"],
      ["the", "ต้น"],
      ["tree", "ไม้"],
    ],
    [
      ["The", "ตัว"],
      ["hare", "กระต่าย"],
      ["woke", "ตื่น"],
      ["but", "แต่"],
      ["he", "เขา"],
      ["arrived", "ไปถึง"],
      ["too", "สาย"],
      ["late", "เกินไป"],
    ],
    [
      ["Slow", "ช้า"],
      ["and", "และ"],
      ["steady", "มั่นคง"],
      ["still", "ก็ยัง"],
      ["won", "ชนะ"],
      ["the", "การ"],
      ["sunny", "ในวันที่"],
      ["race", "แข่ง"],
    ],
  ], hareScenes),
  ...story("เด็กหญิงผ้าคลุมแดง", [
    [
      ["A", "เด็ก"],
      ["girl", "หญิง"],
      ["wearing", "ที่ใส่"],
      ["a", "ผ้า"],
      ["red", "แดง"],
      ["cloak", "คลุม"],
      ["visited", "ไปหา"],
      ["Grandma", "คุณย่า"],
    ],
    [
      ["She", "เธอ"],
      ["carried", "ถือ"],
      ["cake", "เค้ก"],
      ["and", "กับ"],
      ["fruit", "ผลไม้"],
      ["in", "ใน"],
      ["her", "ของเธอ"],
      ["basket", "ตะกร้า"],
    ],
    [
      ["A", "ตัว"],
      ["hungry", "หิว"],
      ["wolf", "หมาป่า"],
      ["stopped", "หยุด"],
      ["her", "เธอ"],
      ["on", "บน"],
      ["the", "ทาง"],
      ["path", "เดิน"],
    ],
    [
      ["Where", "ที่ไหน"],
      ["are", "กำลัง"],
      ["you", "เธอ"],
      ["going", "ไป"],
      ["today", "วันนี้"],
      ["little", "น้อย"],
      ["girl", "หนู"],
      ["he", "เขา"],
      ["asked", "ถาม"],
    ],
    [
      ["I", "ฉัน"],
      ["am", "กำลัง"],
      ["going", "ไป"],
      ["to", "หา"],
      ["visit", "เยี่ยม"],
      ["my", "ของฉัน"],
      ["sick", "ที่ไม่สบาย"],
      ["Grandma", "คุณย่า"],
    ],
    [
      ["The", "ตัว"],
      ["wolf", "หมาป่า"],
      ["reached", "ไปถึง"],
      ["the", "บ้าน"],
      ["house", "นั้น"],
      ["before", "ก่อน"],
      ["the", "เด็ก"],
      ["girl", "หญิง"],
    ],
    [
      ["He", "เขา"],
      ["put", "สวม"],
      ["on", "ไว้"],
      ["her", "ของย่า"],
      ["cap", "หมวก"],
      ["and", "แล้ว"],
      ["lay", "นอน"],
      ["in", "บน"],
      ["bed", "เตียง"],
    ],
    [
      ["What", "ช่าง"],
      ["big", "ใหญ่"],
      ["eyes", "ตา"],
      ["you", "เธอ"],
      ["have", "มี"],
      ["said", "พูด"],
      ["the", "เด็ก"],
      ["girl", "หญิง"],
    ],
    [
      ["A", "คน"],
      ["hunter", "พราน"],
      ["heard", "ได้ยิน"],
      ["her", "เธอ"],
      ["and", "แล้ว"],
      ["chased", "ไล่"],
      ["the", "ตัว"],
      ["wolf", "หมาป่า"],
    ],
  ], redScenes),
];

/** Same three tales, told with B1 wording. Scenes stay in the same order. */
export const talesB1: Token[][] = [
  ...story("สิงโตกับหนู", [
    [
      ["A", "ตัว"],
      ["great", "ใหญ่"],
      ["lion", "สิงโต"],
      ["was", "กำลัง"],
      ["resting", "พัก"],
      ["beneath", "ใต้"],
      ["a", "ต้น"],
      ["tall", "สูง"],
      ["tree", "ไม้"],
    ],
    [
      ["A", "ตัว"],
      ["small", "เล็ก"],
      ["mouse", "หนู"],
      ["scurried", "วิ่งว่อง"],
      ["across", "ผ่าน"],
      ["his", "ของเขา"],
      ["open", "ที่แบ"],
      ["paw", "อุ้งเท้า"],
    ],
    [
      ["The", "ตัว"],
      ["startled", "ที่ตกใจ"],
      ["lion", "สิงโต"],
      ["woke", "ตื่น"],
      ["and", "แล้ว"],
      ["seized", "คว้า"],
      ["the", "ตัว"],
      ["mouse", "หนู"],
    ],
    [
      ["Please", "โปรด"],
      ["spare", "ไว้ชีวิต"],
      ["me", "ฉัน"],
      ["and", "แล้ว"],
      ["I", "ฉัน"],
      ["may", "อาจ"],
      ["help", "ช่วย"],
      ["someday", "สักวัน"],
    ],
    [
      ["The", "ตัว"],
      ["generous", "ใจกว้าง"],
      ["lion", "สิงโต"],
      ["smiled", "ยิ้ม"],
      ["and", "แล้ว"],
      ["released", "ปล่อย"],
      ["the", "ตัว"],
      ["mouse", "หนู"],
    ],
    [
      ["Hunters", "พราน"],
      ["trapped", "ดัก"],
      ["the", "ตัว"],
      ["tired", "ที่เหนื่อย"],
      ["lion", "สิงโต"],
      ["inside", "ใน"],
      ["a", "ผืน"],
      ["net", "ตาข่าย"],
    ],
    [
      ["The", "ตัว"],
      ["mouse", "หนู"],
      ["heard", "ได้ยิน"],
      ["his", "ของเขา"],
      ["cry", "เสียงร้อง"],
      ["and", "แล้ว"],
      ["returned", "กลับมา"],
      ["to", "เพื่อ"],
      ["help", "ช่วย"],
    ],
    [
      ["She", "เธอ"],
      ["gnawed", "แทะ"],
      ["the", "เส้น"],
      ["ropes", "เชือก"],
      ["until", "จน"],
      ["the", "ตัว"],
      ["lion", "สิงโต"],
      ["escaped", "หลุดออก"],
    ],
    [
      ["You", "เธอ"],
      ["saved", "ช่วย"],
      ["me", "ฉัน"],
      ["today", "วันนี้"],
      ["said", "พูด"],
      ["the", "ตัว"],
      ["grateful", "ที่ซาบซึ้ง"],
      ["lion", "สิงโต"],
    ],
  ], lionScenes),
  ...story("เต่ากับกระต่าย", [
    [
      ["A", "ตัว"],
      ["boastful", "ที่โอ้อวด"],
      ["hare", "กระต่าย"],
      ["mocked", "เยาะ"],
      ["the", "ตัว"],
      ["patient", "ที่อดทน"],
      ["tortoise", "เต่า"],
    ],
    [
      ["Shall", "เรา"],
      ["we", "จะ"],
      ["race", "แข่ง"],
      ["toward", "ไปยัง"],
      ["that", "ต้น"],
      ["distant", "ที่ไกล"],
      ["tree", "ไม้"],
      ["he", "เขา"],
      ["asked", "ถาม"],
    ],
    [
      ["The", "ตัว"],
      ["hare", "กระต่าย"],
      ["sprinted", "พุ่ง"],
      ["ahead", "นำ"],
      ["and", "แล้ว"],
      ["paused", "หยุด"],
      ["for", "เพื่อ"],
      ["rest", "พัก"],
    ],
    [
      ["He", "เขา"],
      ["dozed", "งีบ"],
      ["under", "ใต้"],
      ["a", "ต้น"],
      ["tree", "ไม้"],
      ["beside", "ข้าง"],
      ["the", "เส้น"],
      ["road", "ทาง"],
    ],
    [
      ["The", "ตัว"],
      ["tortoise", "เต่า"],
      ["continued", "เดินต่อ"],
      ["without", "โดย"],
      ["a", "ไม่"],
      ["single", "ได้"],
      ["stop", "หยุด"],
    ],
    [
      ["She", "เธอ"],
      ["passed", "ผ่าน"],
      ["the", "ตัว"],
      ["hare", "กระต่าย"],
      ["who", "ที่"],
      ["was", "ยัง"],
      ["still", "คง"],
      ["asleep", "หลับอยู่"],
    ],
    [
      ["The", "ตัว"],
      ["hare", "กระต่าย"],
      ["awoke", "ตื่น"],
      ["but", "แต่"],
      ["reached", "ไปถึง"],
      ["the", "ต้น"],
      ["tree", "ไม้"],
      ["late", "สาย"],
    ],
    [
      ["Patience", "ความอดทน"],
      ["and", "กับ"],
      ["steady", "ความ"],
      ["effort", "สม่ำเสมอ"],
      ["won", "ทำให้ชนะ"],
      ["the", "การ"],
      ["race", "แข่ง"],
    ],
  ], hareScenes),
  ...story("เด็กหญิงผ้าคลุมแดง", [
    [
      ["A", "เด็ก"],
      ["girl", "หญิง"],
      ["in", "ใน"],
      ["a", "ผ้า"],
      ["scarlet", "แดง"],
      ["cloak", "คลุม"],
      ["left", "ออก"],
      ["for", "ไปหา"],
      ["Grandma", "คุณย่า"],
    ],
    [
      ["She", "เธอ"],
      ["carried", "ถือ"],
      ["fresh", "สด"],
      ["cake", "เค้ก"],
      ["and", "กับ"],
      ["fruit", "ผลไม้"],
      ["for", "ให้"],
      ["Grandma", "คุณย่า"],
    ],
    [
      ["A", "ตัว"],
      ["cunning", "เจ้าเล่ห์"],
      ["wolf", "หมาป่า"],
      ["blocked", "ขวาง"],
      ["her", "เธอ"],
      ["on", "บน"],
      ["the", "ทาง"],
      ["path", "เดิน"],
    ],
    [
      ["Where", "ที่ไหน"],
      ["are", "กำลัง"],
      ["you", "เธอ"],
      ["going", "ไป"],
      ["this", "เช้า"],
      ["morning", "นี้"],
      ["he", "เขา"],
      ["asked", "ถาม"],
    ],
    [
      ["I", "ฉัน"],
      ["am", "กำลัง"],
      ["taking", "เอา"],
      ["food", "อาหาร"],
      ["to", "ไปให้"],
      ["my", "ของฉัน"],
      ["ill", "ที่ไม่สบาย"],
      ["Grandma", "คุณย่า"],
    ],
    [
      ["The", "ตัว"],
      ["wolf", "หมาป่า"],
      ["hurried", "รีบ"],
      ["ahead", "ไปก่อน"],
      ["and", "แล้ว"],
      ["reached", "ไปถึง"],
      ["the", "กระท่อม"],
      ["cottage", "นั้น"],
    ],
    [
      ["He", "เขา"],
      ["wore", "สวม"],
      ["her", "ของย่า"],
      ["cap", "หมวก"],
      ["and", "แล้ว"],
      ["waited", "รอ"],
      ["in", "บน"],
      ["the", "เตียง"],
      ["bed", "นั้น"],
    ],
    [
      ["What", "ช่าง"],
      ["large", "โต"],
      ["eyes", "ตา"],
      ["you", "เธอ"],
      ["have", "มี"],
      ["she", "เธอ"],
      ["said", "พูด"],
      ["bravely", "อย่างกล้า"],
    ],
    [
      ["A", "คน"],
      ["hunter", "พราน"],
      ["heard", "ได้ยิน"],
      ["her", "เธอ"],
      ["and", "แล้ว"],
      ["drove", "ไล่"],
      ["the", "ตัว"],
      ["wolf", "หมาป่า"],
      ["off", "ออกไป"],
    ],
  ], redScenes),
];

const packs: Record<Level, { sentences: Token[][]; tales: Token[][] }> = {
  A1: { sentences, tales },
  A2: { sentences: sentencesA2, tales: talesA2 },
  B1: { sentences: sentencesB1, tales: talesB1 },
  B2: { sentences: sentencesB2, tales: talesB2 },
  C1: { sentences: sentencesC1, tales: talesC1 },
  C2: { sentences: sentencesC2, tales: talesC2 },
};

export function assertContent(): void {
  for (const pack of Object.values(packs)) {
    if (pack.sentences.length < 20) throw new Error("Need at least 20 sentences per level");
    for (const sentence of [...pack.sentences, ...pack.tales]) {
      if (sentence.length < 6 || sentence.length > 12) {
        throw new Error(`Sentence length out of range: ${sentence.map((t) => t.en).join(" ")}`);
      }
      for (const token of sentence) {
        if (!/^[A-Za-z'-]+$/.test(token.en) || token.th.length === 0) {
          throw new Error(`Bad token: ${token.en}`);
        }
      }
    }
  }
}

function shuffle<T>(items: T[]): T[] {
  const copy = [...items];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const swap = copy[i];
    copy[i] = copy[j];
    copy[j] = swap;
  }
  return copy;
}

export function sentenceQueue(level: Level): Token[] {
  const deck = shuffle(packs[level].sentences).flat();
  return [...deck, ...deck];
}

export function taleQueue(level: Level): Token[] {
  return packs[level].tales.flat();
}

export function wordQueue(level: Level): Token[] {
  const unique = new Map<string, Token>();
  for (const token of packs[level].sentences.flat()) {
    unique.set(`${token.en}\0${token.th}`, { en: token.en, th: token.th });
  }
  const deck = shuffle([...unique.values()]);
  return [...deck, ...deck, ...deck];
}

export function drillQueue(tokens: Token[], min = 24): Token[] {
  if (tokens.length === 0) return [];
  const clean = tokens.map((token) => ({ en: token.en, th: token.th }));
  const out: Token[] = [];
  while (out.length < Math.max(min, clean.length)) out.push(...clean);
  return out;
}
