/** Natural Thai for each tale line, keyed by its English sentence. */
const taleLines: Record<string, string> = {
  "A big lion sleeps under a tall tree": "สิงโตตัวใหญ่นอนหลับอยู่ใต้ต้นไม้สูง",
  "A small mouse runs across his big paw": "หนูตัวเล็กวิ่งผ่านอุ้งเท้าใหญ่ของเขา",
  "The lion wakes and catches the little mouse": "สิงโตตื่นขึ้นแล้วจับหนูตัวน้อยไว้",
  "Please let me go says the little mouse": "หนูตัวน้อยพูดว่า ปล่อยฉันไปเถอะ",
  "The kind lion smiles and lets the mouse go": "สิงโตใจดียิ้มแล้วปล่อยหนูไป",
  "Some hunters catch the lion in a strong net": "พวกพรานจับสิงโตไว้ในตาข่ายที่แข็งแรง",
  "The mouse hears him and runs back to help": "หนูได้ยินเสียงเขาแล้ววิ่งกลับไปช่วย",
  "She bites the net until the lion is free": "หนูแทะตาข่ายจนสิงโตเป็นอิสระ",
  "Thank you my little friend says the happy lion": "สิงโตดีใจพูดว่า ขอบคุณนะเพื่อนตัวน้อย",

  "A fast hare laughs at a slow tortoise": "กระต่ายที่วิ่งเร็วหัวเราะเยาะเต่าที่เดินช้า",
  "Let us race to that big tree says the hare": "กระต่ายพูดว่า มาแข่งกันไปที่ต้นไม้ใหญ่ต้นนั้นกันเถอะ",
  "The hare runs far ahead and stops to rest": "กระต่ายวิ่งนำหน้าไปไกลแล้วหยุดพัก",
  "He sleeps under a tree beside the long road": "เขานอนหลับใต้ต้นไม้ข้างทางที่ยาว",
  "The slow tortoise keeps walking and does not stop": "เต่าที่เดินช้ายังเดินต่อไปและไม่หยุด",
  "She passes the sleeping hare and walks to the tree": "เธอเดินผ่านกระต่ายที่หลับอยู่แล้วไปถึงต้นไม้",
  "The hare wakes and runs but he is too late": "กระต่ายตื่นแล้ววิ่งตาม แต่ก็สายเกินไป",
  "Slow and steady wins the race that sunny day": "ช้าแต่สม่ำเสมอชนะการแข่งในวันที่มีแดดนั้น",

  "A girl in a red cloak walks to Grandma": "เด็กหญิงในผ้าคลุมสีแดงเดินไปหาคุณย่า",
  "She carries cake and fresh fruit in her basket": "เธอถือตะกร้าที่มีเค้กกับผลไม้สด",
  "A hungry wolf stops her on the forest path": "หมาป่าที่หิวหยุดเธอไว้บนทางในป่า",
  "Where are you going today little girl asks the wolf": "หมาป่าถามว่า วันนี้หนูจะไปไหนจ๊ะเด็กน้อย",
  "I am going to my sick Grandma says the girl": "เด็กหญิงพูดว่า หนูจะไปหาคุณย่าที่ป่วย",
  "The wolf runs to the house before the little girl": "หมาป่าวิ่งไปถึงบ้านก่อนเด็กหญิงตัวน้อย",
  "He puts on her cap and lies in the bed": "เขาสวมหมวกของคุณย่าแล้วนอนลงบนเตียง",
  "What big eyes you have says the brave girl": "เด็กหญิงกล้าหาญพูดว่า ตาโตจังเลยนะ",
  "A hunter hears her and sends the wolf away": "พรานได้ยินเสียงเธอแล้วไล่หมาป่าไป",

  "A huge lion slept under the shady tree": "สิงโตตัวใหญ่หลับอยู่ใต้ต้นไม้ที่ร่มรื่น",
  "A tiny mouse ran across his heavy paw": "หนูตัวจิ๋ววิ่งผ่านอุ้งเท้าหนักของเขา",
  "The angry lion woke and caught the mouse": "สิงโตโกรธตื่นขึ้นแล้วจับหนูไว้",
  "Please let me go and I will help you": "ปล่อยฉันไปเถอะ แล้วฉันจะช่วยคุณ",
  "The kind lion smiled and let him leave": "สิงโตใจดียิ้มแล้วปล่อยเขาไป",
  "Hunters trapped the strong lion in a net": "พวกพรานดักสิงโตที่แข็งแรงไว้ในตาข่าย",
  "The mouse heard his roar and hurried back": "หนูได้ยินเสียงคำรามแล้วรีบวิ่งกลับมา",
  "She chewed the ropes until he was free": "หนูแทะเชือกจนเขาเป็นอิสระ",
  "Thank you little friend said the grateful lion": "สิงโตที่ซาบซึ้งพูดว่า ขอบคุณนะเพื่อนตัวน้อย",

  "A proud hare laughed at the slow tortoise": "กระต่ายที่หยิ่งหัวเราะเยาะเต่าที่เดินช้า",
  "Let us race to the far tree he said": "เขาพูดว่า มาแข่งกันไปที่ต้นไม้ไกลๆ กันเถอะ",
  "The hare ran ahead and stopped to rest": "กระต่ายวิ่งนำหน้าไปแล้วหยุดพัก",
  "He fell asleep beside the quiet road": "เขานอนหลับข้างทางที่เงียบสงบ",
  "The tortoise kept walking and never stopped": "เต่ายังเดินต่อไปและไม่หยุดเลย",
  "She passed the sleeping hare near the tree": "เธอเดินผ่านกระต่ายที่หลับอยู่ใกล้ต้นไม้",
  "The hare woke but he arrived too late": "กระต่ายตื่นขึ้น แต่ไปถึงสายเกินไป",
  "Slow and steady still won the sunny race": "ช้าแต่สม่ำเสมอก็ยังชนะการแข่งในวันที่แดดจ้า",

  "A girl wearing a red cloak visited Grandma": "เด็กหญิงที่สวมผ้าคลุมสีแดงไปเยี่ยมคุณย่า",
  "She carried cake and fruit in her basket": "เธอถือตะกร้าที่มีเค้กกับผลไม้",
  "A hungry wolf stopped her on the path": "หมาป่าที่หิวหยุดเธอไว้บนทาง",
  "Where are you going today little girl he asked": "เขาถามว่า วันนี้หนูจะไปไหนจ๊ะเด็กน้อย",
  "I am going to visit my sick Grandma": "หนูจะไปเยี่ยมคุณย่าที่ป่วย",
  "The wolf reached the house before the girl": "หมาป่าไปถึงบ้านก่อนเด็กหญิง",
  "He put on her cap and lay in bed": "เขาสวมหมวกของคุณย่าแล้วนอนบนเตียง",
  "What big eyes you have said the girl": "เด็กหญิงพูดว่า ตาโตจังเลยนะ",
  "A hunter heard her and chased the wolf": "พรานได้ยินเสียงเธอแล้วไล่ตามหมาป่า",

  "A great lion was resting beneath a tall tree": "สิงโตตัวใหญ่กำลังพักอยู่ใต้ต้นไม้สูง",
  "A small mouse scurried across his open paw": "หนูตัวเล็กวิ่งปราดผ่านอุ้งเท้าที่แบอยู่ของเขา",
  "The startled lion woke and seized the mouse": "สิงโตที่ตกใจตื่นขึ้นแล้วคว้าหนูไว้",
  "Please spare me and I may help someday": "ไว้ชีวิตฉันเถอะ แล้วสักวันฉันอาจช่วยได้",
  "The generous lion smiled and released the mouse": "สิงโตใจกว้างยิ้มแล้วปล่อยหนูไป",
  "Hunters trapped the tired lion inside a net": "พวกพรานดักสิงโตที่เหนื่อยไว้ในตาข่าย",
  "The mouse heard his cry and returned to help": "หนูได้ยินเสียงร้องของเขาแล้วกลับมาช่วย",
  "She gnawed the ropes until the lion escaped": "หนูแทะเชือกจนสิงโตหนีออกมาได้",
  "You saved me today said the grateful lion": "สิงโตที่ซาบซึ้งพูดว่า วันนี้เธอช่วยฉันไว้",

  "A boastful hare mocked the patient tortoise": "กระต่ายที่โอ้อวดเยาะเย้ยเต่าที่อดทน",
  "Shall we race toward that distant tree he asked": "เขาถามว่า เราจะแข่งกันไปที่ต้นไม้ไกลต้นนั้นไหม",
  "The hare sprinted ahead and paused for rest": "กระต่ายพุ่งนำหน้าไปแล้วหยุดพัก",
  "He dozed under a tree beside the road": "เขาเคลิ้มหลับใต้ต้นไม้ข้างทาง",
  "The tortoise continued without a single stop": "เต่าเดินต่อไปโดยไม่หยุดเลยสักครั้ง",
  "She passed the hare who was still asleep": "เธอเดินผ่านกระต่ายที่ยังหลับอยู่",
  "The hare awoke but reached the tree late": "กระต่ายตื่นขึ้นแต่ไปถึงต้นไม้ช้า",
  "Patience and steady effort won the race": "ความอดทนกับการพยายามอย่างสม่ำเสมอชนะการแข่ง",

  "A girl in a scarlet cloak left for Grandma": "เด็กหญิงในผ้าคลุมสีแดงสดออกเดินทางไปหาคุณย่า",
  "She carried fresh cake and fruit for Grandma": "เธอถือเค้กสดกับผลไม้ไปให้คุณย่า",
  "A cunning wolf blocked her on the path": "หมาป่าเจ้าเล่ห์ขวางเธอไว้บนทาง",
  "Where are you going this morning he asked": "เขาถามว่า เช้านี้เธอจะไปไหน",
  "I am taking food to my ill Grandma": "หนูกำลังเอาอาหารไปให้คุณย่าที่ป่วย",
  "The wolf hurried ahead and reached the cottage": "หมาป่ารีบไปก่อนแล้วไปถึงกระท่อม",
  "He wore her cap and waited in the bed": "เขาสวมหมวกของคุณย่าแล้วรออยู่ในเตียง",
  "What large eyes you have she said bravely": "เธอพูดอย่างกล้าหาญว่า ตาโตจังเลยนะ",
  "A hunter heard her and drove the wolf off": "พรานได้ยินเสียงเธอแล้วขับไล่หมาป่าไป",

  "A weary lion lay asleep beneath the ancient tree": "สิงโตที่เหนื่อยล้านอนหลับอยู่ใต้ต้นไม้เก่าแก่",
  "A daring mouse darted across his enormous paw": "หนูที่กล้าได้กล้าเสียวิ่งปราดผ่านอุ้งเท้ามหึมาของเขา",
  "The furious lion woke and pinned the mouse down": "สิงโตที่โกรธจัดตื่นขึ้นแล้วกดหนูไว้",
  "Spare me now and I shall repay you later": "ไว้ชีวิตฉันตอนนี้เถอะ แล้วภายหลังฉันจะตอบแทน",
  "Moved by the plea the lion released the mouse": "สิงโตซาบซึ้งกับคำวิงวอนแล้วปล่อยหนูไป",
  "Hunters trapped the exhausted lion beneath a net": "พวกพรานดักสิงโตที่หมดแรงไว้ใต้ตาข่าย",
  "The mouse recognized his roar and rushed to help": "หนูจำเสียงคำรามของเขาได้แล้วรีบไปช่วย",
  "She gnawed through the ropes until he broke free": "หนูแทะเชือกจนขาด แล้วเขาก็หลุดออกมา",
  "I owe you my freedom said the humbled lion": "สิงโตที่ถ่อมตัวลงพูดว่า ฉันเป็นหนี้เสรีภาพนี้กับเธอ",

  "A boastful hare ridiculed the tortoise for being slow": "กระต่ายที่โอ้อวดเยาะเย้ยเต่าว่าเดินช้า",
  "Let us settle this with a race to that tree": "มาตัดสินกันด้วยการแข่งไปที่ต้นไม้นั้นกันเถอะ",
  "The hare surged ahead and decided he could rest": "กระต่ายพุ่งนำหน้าไปแล้วคิดว่าพักได้",
  "He dozed beside the road convinced victory was his": "เขาเคลิ้มหลับข้างทาง เพราะมั่นใจว่าชนะอยู่แล้ว",
  "The tortoise maintained a steady pace without pausing": "เต่ารักษาจังหวะให้สม่ำเสมอโดยไม่หยุดพัก",
  "She overtook the hare while he was still asleep": "เธอแซงกระต่ายในขณะที่เขายังหลับอยู่",
  "The hare sprang up only to find he was late": "กระต่ายผุดลุกขึ้นมา แต่ก็พบว่าตัวเองสายไปแล้ว",
  "Consistency rather than speed decided the race that day": "วันนั้นความสม่ำเสมอเป็นตัวตัดสินการแข่ง",

  "A girl in a red cloak set out for Grandma": "เด็กหญิงในผ้าคลุมสีแดงออกเดินทางไปหาคุณย่า",
  "Her basket held cake and fruit meant for Grandma": "ในตะกร้าของเธอมีเค้กกับผลไม้ที่ตั้งใจเอาไปให้คุณย่า",
  "A scheming wolf intercepted her along the forest path": "หมาป่าที่วางแผนดักเธอไว้ระหว่างทางในป่า",
  "Where exactly are you heading this morning he inquired": "เขาถามว่า เช้านี้เธอจะไปที่ไหนกันแน่",
  "I am bringing food to my grandmother who is ill": "หนูกำลังเอาอาหารไปให้คุณย่าที่ป่วยอยู่",
  "The wolf slipped ahead and reached the cottage first": "หมาป่าลอบไปก่อนแล้วไปถึงกระท่อมเป็นคนแรก",
  "He disguised himself in her cap and waited in bed": "เขาปลอมตัวด้วยหมวกของคุณย่าแล้วรออยู่ในเตียง",
  "What strikingly large eyes you have the girl observed": "เด็กหญิงพูดว่า ตาโตจนน่าตกใจเลยนะ",
  "A hunter overheard her and forced the wolf to flee": "พรานได้ยินเธอพูดแล้วบังคับให้หมาป่าหนีไป",

  "A magnificent lion dozed in the shade of an oak": "สิงโตสง่างามเคลิ้มหลับในร่มของต้นโอ๊ก",
  "A trembling mouse scurried over his outstretched paw": "หนูที่ตัวสั่นวิ่งปราดผ่านอุ้งเท้าที่เหยียดออกของเขา",
  "Startled from sleep the lion seized the tiny creature": "สิงโตสะดุ้งตื่นแล้วคว้าสัตว์ตัวจิ๋วนั้นไว้",
  "Grant me mercy and I may prove useful someday": "เมตตาฉันเถอะ แล้วสักวันฉันอาจพิสูจน์ว่ามีประโยชน์",
  "Amused rather than angry the lion let him go": "สิงโตรู้สึกขบขันจึงปล่อยเขาไป",
  "Hunters ensnared the weakened lion in a heavy net": "พวกพรานคล้องสิงโตที่อ่อนแรงไว้ในตาข่ายหนัก",
  "Hearing his distress the mouse hurried back to help": "เมื่อได้ยินเสียงร้องขอความช่วยเหลือ หนูรีบกลับมาช่วย",
  "She severed the cords until the lion struggled free": "หนูขบเชือกจนขาด แล้วสิงโตก็ดิ้นจนหลุด",
  "Your courage saved me said the astonished lion": "สิงโตที่ตกตะลึงพูดว่า ความกล้าของเธอช่วยฉันไว้",

  "An arrogant hare mocked the tortoise for her patience": "กระต่ายที่หยิ่งผยองเยาะเย้ยความอดทนของเต่า",
  "Shall we prove who is faster by racing to that tree": "เราจะพิสูจน์กันไหมว่าใครเร็วกว่า ด้วยการแข่งไปที่ต้นไม้นั้น",
  "Confident of victory the hare raced far ahead": "กระต่ายมั่นใจว่าจะชนะจึงวิ่งนำหน้าไปไกล",
  "He settled down for a nap beside the road": "เขานอนลงงีบข้างทาง",
  "The tortoise persisted and refused to break stride": "เต่ามุ่งเดินต่อไปโดยไม่ให้จังหวะสะดุด",
  "She slipped past the hare who had not yet stirred": "เธอเดินลัดผ่านกระต่ายที่ยังไม่ขยับตัว",
  "The hare awoke and realized the finish was taken": "กระต่ายตื่นขึ้นแล้วรู้ว่าเส้นชัยมีคนไปถึงแล้ว",
  "Steady persistence outperformed raw speed that afternoon": "บ่ายวันนั้นความมุ่งมั่นที่สม่ำเสมอเอาชนะความเร็วล้วนๆ",

  "A girl wrapped in a crimson cloak departed for Grandma": "เด็กหญิงที่ห่มผ้าคลุมสีแดงเข้มออกเดินทางไปหาคุณย่า",
  "She carried freshly baked cake and fruit as a gift": "เธอถือเค้กอบใหม่กับผลไม้ไปเป็นของขวัญ",
  "A calculating wolf waylaid her on the woodland path": "หมาป่าที่คิดคำนวณดักเธอไว้บนทางในป่า",
  "Where might you be going on this fine morning": "เช้าที่อากาศดีแบบนี้ เธอจะไปไหนหรือ",
  "I am delivering food to my grandmother who is unwell": "หนูกำลังเอาอาหารไปให้คุณย่าที่ไม่สบาย",
  "The wolf outpaced her and slipped into the cottage": "หมาป่าวิ่งเร็วกว่าเธอแล้วลอบเข้าไปในกระท่อม",
  "Disguised in Grandma's cap he lay waiting in bed": "เขาปลอมตัวด้วยหมวกของคุณย่าแล้วนอนรออยู่ในเตียง",
  "What remarkably large eyes you have she remarked uneasily": "เธอพูดอย่างไม่สบายใจว่า ตาโตผิดปกติเลยนะ",
  "A hunter nearby intervened and drove the wolf away": "พรานที่อยู่ใกล้ๆ เข้ามาขวางแล้วไล่หมาป่าไป",

  "A formidable lion slumbered beneath the spreading oak": "สิงโตที่น่าเกรงขามหลับใหลอยู่ใต้ต้นโอ๊กที่แผ่กิ่งก้าน",
  "An audacious mouse traversed his immense resting paw": "หนูที่บังอาจเดินข้ามอุ้งเท้ามหึมาที่เขาวางพักอยู่",
  "The indignant lion awoke and clamped the mouse fast": "สิงโตที่ขุ่นเคืองตื่นขึ้นแล้วหนีบหนูไว้แน่น",
  "Show clemency and I may yet repay your mercy": "โปรดเมตตาเถอะ แล้วฉันอาจตอบแทนความกรุณานี้ได้",
  "The lion relented and released his unlikely captive": "สิงโตใจอ่อนแล้วปล่อยหนูที่ถูกจับไว้ไป",
  "Hunters entangled the formidable lion in a knotted net": "พวกพรานพันสิงโตที่น่าเกรงขามไว้ในตาข่ายที่ผูกปม",
  "Alerted by his roar the mouse hastened back to assist": "หนูได้ยินเสียงคำรามจึงรีบกลับมาช่วย",
  "She frayed the bindings until the lion tore free": "หนูขบเชือกที่มัดไว้จนหลุด แล้วสิงโตก็ฉีกตัวออกมา",
  "I am indebted to you murmured the chastened lion": "สิงโตที่สำนึกตัวพูดเบาๆ ว่า ฉันเป็นหนี้บุญคุณเธอ",

  "A vainglorious hare derided the tortoise as hopelessly slow": "กระต่ายที่หลงตัวเองดูถูกเต่าว่าช้าจนไม่มีทางชนะ",
  "He proposed a race to the distant tree as proof": "เขาเสนอให้แข่งไปที่ต้นไม้ไกลๆ เพื่อพิสูจน์",
  "Certain of triumph the hare bolted into the lead": "กระต่ายมั่นใจว่าจะชนะจึงพุ่งขึ้นนำ",
  "He succumbed to drowsiness beside the sunlit road": "เขาผลอยหลับข้างทางที่มีแสงแดด",
  "The tortoise advanced with unwavering unbroken concentration": "เต่าเดินหน้าต่อไปด้วยสมาธิที่ไม่สะดุด",
  "She glided past the hare while his confidence slept": "เธอเดินผ่านกระต่ายที่ยังหลับเพราะมั่นใจเกินไป",
  "The hare lurched awake and discovered he had lost": "กระต่ายสะดุ้งตื่นแล้วพบว่าตัวเองแพ้แล้ว",
  "Unspectacular persistence prevailed over dazzling careless speed": "ความพยายามที่เรียบง่ายเอาชนะความเร็วที่ฉูดฉาดแต่ไม่ระวัง",

  "Cloaked in scarlet the girl ventured toward Grandma's cottage": "เด็กหญิงในผ้าคลุมสีแดงเข้มออกเดินทางไปยังกระท่อมของคุณย่า",
  "The basket contained cake and fruit intended for Grandma": "ในตะกร้ามีเค้กกับผลไม้ที่ตั้งใจเอาไปให้คุณย่า",
  "A predatory wolf accosted her upon the forest path": "หมาป่านักล่าเข้าไปทักเธอบนทางในป่า",
  "Where precisely are you bound this morning he asked": "เขาถามว่า เช้านี้เธอจะมุ่งไปที่ไหนกันแน่",
  "I am conveying provisions to my ailing grandmother": "หนูกำลังเอาเสบียงไปให้คุณย่าที่ป่วย",
  "The wolf preceded her and gained the cottage unseen": "หมาป่าไปก่อนเธอแล้วเข้ากระท่อมโดยไม่มีใครเห็น",
  "Swathed in her cap he reclined in the waiting bed": "เขาคลุมตัวด้วยหมวกของคุณย่าแล้วนอนรออยู่ในเตียง",
  "What prodigious eyes you possess she observed warily": "เธอพูดอย่างระแวงว่า ตาโตมหึมาเลยนะ",
  "A hunter interposed and compelled the wolf to withdraw": "พรานเข้ามาขวางแล้วบังคับให้หมาป่าถอยไป",
};

export function taleSentence(english: string): string {
  const thai = taleLines[english];
  if (!thai) throw new Error(`Missing tale sentence: ${english}`);
  return thai;
}
