import { taleSentence } from "./tale-lines";
import type { Token } from "./types";

function line(pairs: [string, string][]): Token[] {
  const tokens: Token[] = pairs.map(([en, th]) => ({ en, th }));
  const last = tokens[tokens.length - 1];
  if (last) last.sentenceEnd = true;
  return tokens;
}

function story(title: string, lines: [string, string][][], scenes: string[]): Token[][] {
  if (scenes.length !== lines.length) {
    throw new Error(`${title}: ${scenes.length} scenes for ${lines.length} lines`);
  }
  return lines.map((pairs, index) => {
    const tokens = line(pairs);
    const sentenceTh = taleSentence(tokens.map((token) => token.en).join(" "));
    for (const token of tokens) {
      token.tale = title;
      token.scene = scenes[index];
      token.sentenceTh = sentenceTh;
    }
    return tokens;
  });
}

const lionScenes = [
  "lion-sleep",
  "lion-paw",
  "lion-catch",
  "lion-please",
  "lion-lets",
  "lion-net",
  "lion-runs",
  "lion-bites",
  "lion-thanks",
];

const hareScenes = [
  "hare-laugh",
  "hare-start",
  "hare-ahead",
  "hare-sleep",
  "tortoise-walk",
  "tortoise-pass",
  "hare-late",
  "tortoise-win",
];

const redScenes = [
  "red-walk",
  "red-basket",
  "red-stop",
  "red-ask",
  "red-answer",
  "wolf-house",
  "wolf-bed",
  "red-eyes",
  "hunter",
];

/** B2: opinion, consequence, and less everyday wording. */
export const sentencesB2: Token[][] = [
  line([
    ["The", "หลัก"],
    ["evidence", "ฐาน"],
    ["suggests", "ชี้ว่า"],
    ["a", "การ"],
    ["significant", "สำคัญ"],
    ["change", "เปลี่ยนแปลง"],
    ["in", "ของ"],
    ["climate", "สภาพอากาศ"],
  ]),
  line([
    ["She", "เธอ"],
    ["was", "ได้"],
    ["offered", "รับ"],
    ["a", "โอกาส"],
    ["better", "ที่ดีกว่า"],
    ["opportunity", "นั้น"],
    ["abroad", "ต่างประเทศ"],
    ["last", "ปี"],
    ["year", "ที่แล้ว"],
  ]),
  line([
    ["We", "เรา"],
    ["should", "ควร"],
    ["consider", "คิดถึง"],
    ["the", "ผล"],
    ["consequences", "ที่ตามมา"],
    ["before", "ก่อน"],
    ["we", "เรา"],
    ["decide", "ตัดสินใจ"],
  ]),
  line([
    ["He", "เขา"],
    ["recommended", "แนะนำ"],
    ["a", "วิธี"],
    ["quieter", "ที่เงียบกว่า"],
    ["approach", "เข้าหา"],
    ["during", "ระหว่าง"],
    ["the", "การ"],
    ["meeting", "ประชุม"],
  ]),
  line([
    ["Despite", "แม้"],
    ["the", "ความ"],
    ["delay", "ล่าช้า"],
    ["the", "ทีม"],
    ["team", "นั้น"],
    ["managed", "ก็ทำ"],
    ["to", "ได้"],
    ["finish", "เสร็จ"],
  ]),
  line([
    ["I", "ฉัน"],
    ["would", "จะ"],
    ["travel", "เดินทาง"],
    ["more", "มากกว่านี้"],
    ["if", "ถ้า"],
    ["I", "ฉัน"],
    ["had", "มี"],
    ["enough", "พอ"],
    ["time", "เวลา"],
  ]),
  line([
    ["They", "พวกเขา"],
    ["are", "เป็น"],
    ["responsible", "ผู้รับผิดชอบ"],
    ["for", "ใน"],
    ["keeping", "การเก็บ"],
    ["the", "บันทึก"],
    ["records", "นั้น"],
    ["accurate", "ให้ถูกต้อง"],
  ]),
  line([
    ["Whether", "ไม่ว่า"],
    ["you", "คุณ"],
    ["agree", "จะเห็นด้วย"],
    ["or", "หรือ"],
    ["not", "ไม่"],
    ["the", "แผน"],
    ["plan", "นั้น"],
    ["continues", "ก็ดำเนินต่อ"],
  ]),
  line([
    ["The", "รายงาน"],
    ["report", "นั้น"],
    ["was", "ถูก"],
    ["written", "เขียน"],
    ["from", "จาก"],
    ["a", "มุม"],
    ["different", "ที่ต่าง"],
    ["perspective", "มอง"],
  ]),
  line([
    ["She", "เธอ"],
    ["managed", "สามารถ"],
    ["to", "ได้"],
    ["negotiate", "ต่อรอง"],
    ["a", "ราคา"],
    ["fairer", "ที่ยุติธรรมกว่า"],
    ["price", "นั้น"],
    ["yesterday", "เมื่อวาน"],
  ]),
  line([
    ["We", "เรา"],
    ["need", "ต้อง"],
    ["to", "ไป"],
    ["look", "ตรวจสอบ"],
    ["into", "ให้ชัด"],
    ["the", "สาเหตุ"],
    ["cause", "ของ"],
    ["of", "เรื่อง"],
    ["this", "นี้"],
  ]),
  line([
    ["Public", "ระบบ"],
    ["transport", "ขนส่งสาธารณะ"],
    ["could", "อาจ"],
    ["reduce", "ลด"],
    ["pressure", "แรงกดดัน"],
    ["on", "ต่อ"],
    ["the", "สิ่ง"],
    ["environment", "แวดล้อม"],
  ]),
  line([
    ["He", "เขา"],
    ["assumed", "คิดว่า"],
    ["the", "ข้อความ"],
    ["message", "นั้น"],
    ["had", "ได้"],
    ["already", "ถูก"],
    ["been", "ส่ง"],
    ["sent", "ไปแล้ว"],
  ]),
  line([
    ["The", "ผล"],
    ["results", "ลัพธ์"],
    ["were", "เป็น"],
    ["more", "มาก"],
    ["reliable", "น่าเชื่อถือ"],
    ["than", "กว่า"],
    ["we", "ที่เรา"],
    ["expected", "คาดไว้"],
  ]),
  line([
    ["Please", "โปรด"],
    ["point", "ชี้"],
    ["out", "ให้เห็น"],
    ["any", "ข้อ"],
    ["errors", "ผิด"],
    ["before", "ก่อน"],
    ["Friday", "วันศุกร์"],
    ["morning", "เช้า"],
  ]),
  line([
    ["She", "เธอ"],
    ["has", "ได้"],
    ["been", "ทำ"],
    ["working", "งาน"],
    ["on", "ชิ้น"],
    ["this", "นี้"],
    ["project", "มา"],
    ["since", "ตั้งแต่"],
    ["March", "มีนาคม"],
  ]),
  line([
    ["A", "คำ"],
    ["clear", "อธิบาย"],
    ["explanation", "ที่ชัด"],
    ["would", "จะ"],
    ["help", "ช่วย"],
    ["everyone", "ทุกคน"],
    ["understand", "ให้เข้าใจ"],
    ["faster", "เร็วขึ้น"],
  ]),
  line([
    ["They", "พวกเขา"],
    ["carried", "ทำ"],
    ["out", "การ"],
    ["the", "สำรวจ"],
    ["survey", "นั้น"],
    ["across", "ใน"],
    ["three", "สาม"],
    ["cities", "เมือง"],
  ]),
  line([
    ["I", "ฉัน"],
    ["doubt", "สงสัย"],
    ["that", "ว่า"],
    ["this", "วิธี"],
    ["solution", "แก้นี้"],
    ["will", "จะ"],
    ["last", "อยู่"],
    ["long", "ได้นาน"],
  ]),
  line([
    ["The", "หลักสูตร"],
    ["course", "นี้"],
    ["focuses", "เน้น"],
    ["on", "ทักษะ"],
    ["skills", "ที่"],
    ["you", "คุณ"],
    ["can", "ใช้"],
    ["use", "ได้"],
    ["immediately", "ทันที"],
  ]),
  line([
    ["We", "เรา"],
    ["ran", "หมด"],
    ["out", "เวลา"],
    ["of", "ไป"],
    ["time", "แล้ว"],
    ["before", "ก่อน"],
    ["the", "คำถาม"],
    ["final", "ข้อ"],
    ["question", "สุดท้าย"],
  ]),
  line([
    ["His", "ข้อ"],
    ["argument", "โต้แย้งของเขา"],
    ["sounded", "ฟังดู"],
    ["reasonable", "สมเหตุสมผล"],
    ["but", "แต่"],
    ["lacked", "ขาด"],
    ["strong", "หลักฐาน"],
    ["evidence", "ที่หนักแน่น"],
  ]),
  line([
    ["She", "เธอ"],
    ["tends", "มัก"],
    ["to", "จะ"],
    ["avoid", "หลีก"],
    ["decisions", "การตัดสินใจ"],
    ["under", "เมื่อ"],
    ["heavy", "มีแรง"],
    ["pressure", "กดดันมาก"],
  ]),
  line([
    ["The", "ย่าน"],
    ["neighborhood", "นี้"],
    ["has", "ได้"],
    ["changed", "เปลี่ยน"],
    ["noticeably", "อย่างเห็นได้ชัด"],
    ["over", "ตลอด"],
    ["ten", "สิบ"],
    ["years", "ปี"],
  ]),
];

/** C1: nuance, hedging, and abstract academic wording. */
export const sentencesC1: Token[][] = [
  line([
    ["The", "ข้อ"],
    ["proposal", "เสนอนี้"],
    ["raises", "ก่อ"],
    ["several", "หลาย"],
    ["implications", "นัย"],
    ["we", "ที่เรา"],
    ["cannot", "ไม่"],
    ["ignore", "ควรมองข้าม"],
  ]),
  line([
    ["She", "เธอ"],
    ["was", "ยัง"],
    ["reluctant", "ลังเล"],
    ["to", "ที่จะ"],
    ["elaborate", "อธิบายเพิ่ม"],
    ["on", "ใน"],
    ["the", "ราย"],
    ["details", "ละเอียด"],
  ]),
  line([
    ["Nevertheless", "กระนั้น"],
    ["the", "คณะ"],
    ["committee", "กรรมการ"],
    ["approved", "ก็อนุมัติ"],
    ["a", "งบ"],
    ["substantial", "ก้อนใหญ่"],
    ["budget", "นั้น"],
  ]),
  line([
    ["His", "ของเขา"],
    ["hypothesis", "สมมติฐาน"],
    ["failed", "ไม่สามารถ"],
    ["to", "ที่จะ"],
    ["account", "อธิบาย"],
    ["for", "ถึง"],
    ["recent", "ข้อมูล"],
    ["data", "ล่าสุด"],
  ]),
  line([
    ["We", "เรา"],
    ["need", "ต้อง"],
    ["a", "การ"],
    ["comprehensive", "ทบทวน"],
    ["review", "รอบด้าน"],
    ["before", "ก่อน"],
    ["any", "จะ"],
    ["launch", "เปิดตัว"],
  ]),
  line([
    ["The", "ความ"],
    ["delay", "ล่าช้า"],
    ["was", "เป็น"],
    ["inevitable", "สิ่งที่เลี่ยงไม่ได้"],
    ["given", "เมื่อ"],
    ["the", "เอกสาร"],
    ["missing", "ยัง"],
    ["documents", "ขาด"],
  ]),
  line([
    ["She", "เธอ"],
    ["questioned", "ตั้งคำถาม"],
    ["the", "กับ"],
    ["criteria", "เกณฑ์"],
    ["used", "ที่ใช้"],
    ["to", "จัด"],
    ["rank", "อันดับ"],
    ["candidates", "ผู้สมัคร"],
  ]),
  line([
    ["A", "แผน"],
    ["sustainable", "ที่ยั่งยืน"],
    ["plan", "นั้น"],
    ["requires", "ต้องการ"],
    ["more", "มากกว่า"],
    ["than", "ผล"],
    ["short-term", "ระยะสั้น"],
    ["gains", "เท่านั้น"],
  ]),
  line([
    ["They", "พวกเขา"],
    ["undermined", "บั่นทอน"],
    ["the", "ข้อ"],
    ["agreement", "ตกลง"],
    ["by", "ด้วย"],
    ["changing", "การเปลี่ยน"],
    ["the", "เงื่อนไข"],
    ["terms", "นั้น"],
  ]),
  line([
    ["I", "ฉัน"],
    ["would", "อยาก"],
    ["appreciate", "ได้"],
    ["a", "บท"],
    ["more", "สรุป"],
    ["precise", "ที่แม่นยำ"],
    ["written", "เป็นลายลักษณ์"],
    ["summary", "กว่านี้"],
  ]),
  line([
    ["The", "ข้อ"],
    ["findings", "ค้นพบ"],
    ["remain", "ยัง"],
    ["controversial", "เป็นที่ถกเถียง"],
    ["among", "ในหมู่"],
    ["leading", "นัก"],
    ["researchers", "วิจัยแนวหน้า"],
  ]),
  line([
    ["He", "เขา"],
    ["outlined", "ชี้"],
    ["the", "ความ"],
    ["risks", "เสี่ยง"],
    ["whereas", "ขณะที่"],
    ["she", "เธอ"],
    ["stressed", "เน้น"],
    ["the", "ผล"],
    ["benefits", "ดี"],
  ]),
  line([
    ["This", "แนว"],
    ["approach", "นี้"],
    ["is", "ไม่"],
    ["unlikely", "น่าจะ"],
    ["to", "ก่อ"],
    ["produce", "ผล"],
    ["lasting", "ที่"],
    ["results", "ยั่งยืน"],
  ]),
  line([
    ["Please", "โปรด"],
    ["clarify", "ทำให้ชัด"],
    ["what", "ว่า"],
    ["you", "คุณ"],
    ["mean", "หมายถึง"],
    ["by", "อะไร"],
    ["adequate", "ด้วย"],
    ["evidence", "หลักฐานที่พอ"],
  ]),
  line([
    ["The", "นโยบาย"],
    ["policy", "นี้"],
    ["has", "ส่ง"],
    ["a", "ผล"],
    ["considerable", "ไม่น้อย"],
    ["impact", "ต่อ"],
    ["on", "เมือง"],
    ["rural", "ใน"],
    ["towns", "ชนบท"],
  ]),
  line([
    ["She", "เธอ"],
    ["demonstrated", "แสดง"],
    ["remarkable", "ความ"],
    ["patience", "อดทน"],
    ["throughout", "อย่างน่าทึ่ง"],
    ["the", "ตลอด"],
    ["discussion", "การสนทนา"],
  ]),
  line([
    ["We", "เรา"],
    ["cannot", "ไม่"],
    ["overlook", "ควรมองข้าม"],
    ["the", "บริบท"],
    ["broader", "ที่กว้าง"],
    ["context", "กว่า"],
    ["of", "ของ"],
    ["this", "ประเด็น"],
    ["issue", "นี้"],
  ]),
  line([
    ["His", "คำ"],
    ["explanation", "อธิบาย"],
    ["was", "ของเขา"],
    ["coherent", "สอดคล้อง"],
    ["yet", "แต่"],
    ["far", "ยัง"],
    ["from", "ไม่"],
    ["complete", "ครบ"],
  ]),
  line([
    ["The", "ทีม"],
    ["team", "นั้น"],
    ["adopted", "ใช้"],
    ["a", "กลยุทธ์"],
    ["cautious", "ที่ระวัง"],
    ["strategy", "ตัว"],
    ["after", "หลัง"],
    ["the", "ความ"],
    ["setback", "พ่ายแพ้"],
  ]),
  line([
    ["There", "มี"],
    ["is", "อยู่"],
    ["a", "ความ"],
    ["subtle", "แตกต่าง"],
    ["distinction", "เล็กน้อย"],
    ["between", "ระหว่าง"],
    ["the", "ข้อ"],
    ["two", "อ้าง"],
    ["claims", "สองข้อ"],
  ]),
  line([
    ["She", "เธอ"],
    ["challenged", "ทักท้วง"],
    ["an", "ข้อ"],
    ["assumption", "สมมติ"],
    ["that", "ที่"],
    ["most", "คน"],
    ["people", "ส่วนใหญ่"],
    ["accepted", "ยอมรับ"],
  ]),
  line([
    ["The", "ร่าง"],
    ["draft", "นั้น"],
    ["needs", "ต้อง"],
    ["substantial", "แก้"],
    ["revision", "อย่างมาก"],
    ["before", "ก่อน"],
    ["publication", "เผยแพร่"],
  ]),
  line([
    ["I", "ฉัน"],
    ["remain", "ยัง"],
    ["skeptical", "ไม่ปักใจ"],
    ["until", "จนกว่า"],
    ["the", "ตัวเลข"],
    ["figures", "นั้น"],
    ["are", "จะ"],
    ["verified", "ได้รับการตรวจ"],
  ]),
  line([
    ["Effective", "การ"],
    ["communication", "สื่อสาร"],
    ["depends", "ที่ดี"],
    ["on", "ขึ้นกับ"],
    ["listening", "การฟัง"],
    ["as", "พอๆ"],
    ["well", "กับ"],
    ["as", "การ"],
    ["speaking", "พูด"],
  ]),
];

/** C2: precise wording, where a near-synonym would change the meaning. */
export const sentencesC2: Token[][] = [
  line([
    ["The", "ความ"],
    ["discrepancy", "คลาดเคลื่อน"],
    ["between", "ระหว่าง"],
    ["the", "คำ"],
    ["accounts", "ให้การ"],
    ["remains", "ยัง"],
    ["unresolved", "ไม่ยุติ"],
  ]),
  line([
    ["She", "เธอ"],
    ["scrutinized", "พินิจ"],
    ["the", "สัญญา"],
    ["contract", "นั้น"],
    ["before", "ก่อน"],
    ["signing", "จะ"],
    ["anything", "เซ็น"],
  ]),
  line([
    ["His", "ถ้อย"],
    ["remarks", "คำ"],
    ["were", "ของเขา"],
    ["unequivocal", "ชัดเจนไม่คลุมเครือ"],
    ["and", "และ"],
    ["left", "ไม่"],
    ["no", "เหลือ"],
    ["ambiguity", "ความกำกวม"],
  ]),
  line([
    ["The", "ปัญหา"],
    ["problem", "นี้"],
    ["is", "เป็นสิ่ง"],
    ["intrinsic", "ที่ฝังอยู่"],
    ["to", "ใน"],
    ["the", "วิธี"],
    ["way", "ที่"],
    ["the", "ระบบ"],
    ["system", "นี้"],
    ["works", "ทำงาน"],
  ]),
  line([
    ["They", "พวกเขา"],
    ["sought", "พยายาม"],
    ["to", "จะ"],
    ["circumvent", "เลี่ยง"],
    ["the", "ขั้นตอน"],
    ["usual", "อนุมัติ"],
    ["approval", "ตาม"],
    ["process", "ปกติ"],
  ]),
  line([
    ["A", "บรรณาธิการ"],
    ["meticulous", "ที่ละเอียด"],
    ["editor", "ถี่ถ้วน"],
    ["would", "น่า"],
    ["have", "จะ"],
    ["caught", "จับ"],
    ["that", "ความ"],
    ["inconsistency", "ไม่สอดคล้องนั้นได้"],
  ]),
  line([
    ["The", "ข่าว"],
    ["rumor", "ลือ"],
    ["proved", "นั้น"],
    ["ephemeral", "อยู่ได้ไม่นาน"],
    ["once", "เมื่อ"],
    ["the", "ข้อ"],
    ["facts", "เท็จจริง"],
    ["emerged", "ปรากฏ"],
  ]),
  line([
    ["We", "เรา"],
    ["must", "ไม่"],
    ["not", "ควร"],
    ["exacerbate", "ซ้ำเติม"],
    ["an", "สถานการณ์"],
    ["already", "ที่"],
    ["fragile", "เปราะบาง"],
    ["situation", "อยู่แล้ว"],
  ]),
  line([
    ["Her", "ข้อ"],
    ["argument", "ถก"],
    ["was", "ของเธอ"],
    ["pragmatic", "เน้นทางปฏิบัติ"],
    ["rather", "มากกว่า"],
    ["than", "จะ"],
    ["purely", "เป็น"],
    ["theoretical", "ทฤษฎีล้วน"],
  ]),
  line([
    ["The", "พยาน"],
    ["witnesses", "เหล่านั้น"],
    ["failed", "ไม่"],
    ["to", "สามารถ"],
    ["corroborate", "ยืนยัน"],
    ["his", "ถ้อยคำ"],
    ["detailed", "ละเอียด"],
    ["version", "ของเขา"],
  ]),
  line([
    ["Such", "ลักษณะ"],
    ["idiosyncrasies", "เฉพาะเช่นนี้"],
    ["make", "ทำให้"],
    ["the", "ร้อยแก้ว"],
    ["prose", "นั้น"],
    ["oddly", "แปลกจน"],
    ["memorable", "ติดจำ"],
  ]),
  line([
    ["The", "ความ"],
    ["tension", "ตึงเครียด"],
    ["was", "สัมผัส"],
    ["palpable", "ได้"],
    ["throughout", "ตลอด"],
    ["the", "คำ"],
    ["closing", "กล่าว"],
    ["speech", "ปิด"],
  ]),
  line([
    ["He", "เขา"],
    ["juxtaposed", "วางเทียบ"],
    ["two", "งาน"],
    ["contradictory", "ศึกษา"],
    ["studies", "ที่ขัดกัน"],
    ["without", "โดย"],
    ["comment", "ไม่วิจารณ์"],
  ]),
  line([
    ["Ubiquitous", "จอ"],
    ["screens", "ที่มีทั่วไป"],
    ["have", "ได้"],
    ["altered", "เปลี่ยน"],
    ["how", "วิธี"],
    ["people", "ที่คน"],
    ["sustain", "รักษา"],
    ["attention", "สมาธิ"],
  ]),
  line([
    ["The", "คณะ"],
    ["committee", "กรรมการ"],
    ["issued", "ออก"],
    ["a", "แถลงการณ์"],
    ["terse", "ที่สั้น"],
    ["but", "แต่"],
    ["decisive", "เด็ดขาด"],
    ["statement", "ฉบับนั้น"],
  ]),
  line([
    ["She", "เธอ"],
    ["refused", "ปฏิเสธ"],
    ["to", "ที่จะ"],
    ["condone", "ยอมให้"],
    ["a", "การ"],
    ["practice", "กระทำ"],
    ["she", "ที่เธอ"],
    ["considered", "เห็นว่า"],
    ["unethical", "ผิดจริยธรรม"],
  ]),
  line([
    ["Their", "ความ"],
    ["optimism", "หวัง"],
    ["seemed", "ของพวกเขา"],
    ["premature", "ดูเร็วไป"],
    ["given", "เมื่อ"],
    ["the", "หลัก"],
    ["scant", "ฐาน"],
    ["evidence", "ยังบาง"],
  ]),
  line([
    ["The", "ตอน"],
    ["novel's", "จบ"],
    ["ending", "ของนิยาย"],
    ["is", "ตั้งใจ"],
    ["deliberately", "ให้"],
    ["ambiguous", "กำกวม"],
    ["and", "และ"],
    ["unsettling", "ไม่สบายใจ"],
  ]),
  line([
    ["We", "เรา"],
    ["should", "ควร"],
    ["distinguish", "แยก"],
    ["correlation", "ความสัมพันธ์ร่วม"],
    ["from", "ออกจาก"],
    ["genuine", "เหตุ"],
    ["causation", "ผลจริง"],
  ]),
  line([
    ["His", "คำ"],
    ["apology", "ขอโทษ"],
    ["sounded", "ของเขา"],
    ["perfunctory", "ฟังดูพอเป็นพิธี"],
    ["and", "และ"],
    ["failed", "ไม่"],
    ["to", "สามารถ"],
    ["persuade", "โน้มน้าว"],
  ]),
  line([
    ["The", "กฎหมาย"],
    ["legislation", "ฉบับนี้"],
    ["is", "ยุ่ง"],
    ["cumbersome", "ยาก"],
    ["and", "และ"],
    ["difficult", "บังคับ"],
    ["to", "ใช้"],
    ["enforce", "ได้ยาก"],
  ]),
  line([
    ["She", "เธอ"],
    ["articulated", "กล่าว"],
    ["a", "จุด"],
    ["nuanced", "ยืน"],
    ["position", "ที่ละเอียด"],
    ["under", "ภายใต้"],
    ["intense", "การ"],
    ["questioning", "ตั้งคำถามหนัก"],
  ]),
  line([
    ["Persistent", "ความกำกวม"],
    ["ambiguity", "ที่ค้างอยู่"],
    ["undermines", "บั่นทอน"],
    ["trust", "ความเชื่อมั่น"],
    ["in", "ต่อ"],
    ["the", "ข้อ"],
    ["findings", "ค้นพบนั้น"],
  ]),
  line([
    ["A", "ข้อ"],
    ["concise", "โต้กลับ"],
    ["rebuttal", "ที่กระชับ"],
    ["can", "อาจ"],
    ["be", "เป็น"],
    ["more", "สิ่ง"],
    ["persuasive", "ที่โน้มน้าวได้"],
    ["than", "กว่า"],
    ["length", "ความยาว"],
  ]),
];

export const talesB2: Token[][] = [
  ...story("สิงโตกับหนู", [
    [
      ["A", "ตัว"],
      ["weary", "เหนื่อย"],
      ["lion", "สิงโต"],
      ["lay", "นอน"],
      ["asleep", "หลับ"],
      ["beneath", "ใต้"],
      ["the", "ต้น"],
      ["ancient", "เก่าแก่"],
      ["tree", "ไม้"],
    ],
    [
      ["A", "ตัว"],
      ["daring", "กล้า"],
      ["mouse", "หนู"],
      ["darted", "พุ่ง"],
      ["across", "ผ่าน"],
      ["his", "อุ้ง"],
      ["enormous", "ที่ใหญ่"],
      ["paw", "ของเขา"],
    ],
    [
      ["The", "ตัว"],
      ["furious", "โกรธ"],
      ["lion", "สิงโต"],
      ["woke", "ตื่น"],
      ["and", "แล้ว"],
      ["pinned", "กด"],
      ["the", "หนู"],
      ["mouse", "ไว้"],
      ["down", "กับพื้น"],
    ],
    [
      ["Spare", "ไว้"],
      ["me", "ชีวิต"],
      ["now", "ฉัน"],
      ["and", "ตอนนี้"],
      ["I", "แล้ว"],
      ["shall", "ฉัน"],
      ["repay", "จะ"],
      ["you", "ตอบแทน"],
      ["later", "คุณภายหลัง"],
    ],
    [
      ["Moved", "ซาบซึ้ง"],
      ["by", "กับ"],
      ["the", "คำ"],
      ["plea", "ขอ"],
      ["the", "สิงโต"],
      ["lion", "จึง"],
      ["released", "ปล่อย"],
      ["the", "ตัว"],
      ["mouse", "หนู"],
    ],
    [
      ["Hunters", "พราน"],
      ["trapped", "ดัก"],
      ["the", "ตัว"],
      ["exhausted", "ที่หมดแรง"],
      ["lion", "สิงโต"],
      ["beneath", "ใต้"],
      ["a", "ผืน"],
      ["net", "ตาข่าย"],
    ],
    [
      ["The", "ตัว"],
      ["mouse", "หนู"],
      ["recognized", "จำได้"],
      ["his", "เสียงคำราม"],
      ["roar", "ของเขา"],
      ["and", "แล้ว"],
      ["rushed", "รีบ"],
      ["to", "ไป"],
      ["help", "ช่วย"],
    ],
    [
      ["She", "เธอ"],
      ["gnawed", "แทะ"],
      ["through", "ขาด"],
      ["the", "เส้น"],
      ["ropes", "เชือก"],
      ["until", "จน"],
      ["he", "เขา"],
      ["broke", "หลุด"],
      ["free", "ออกมา"],
    ],
    [
      ["I", "ฉัน"],
      ["owe", "เป็นหนี้"],
      ["you", "เธอ"],
      ["my", "ในเรื่อง"],
      ["freedom", "อิสรภาพ"],
      ["said", "พูด"],
      ["the", "สิงโต"],
      ["humbled", "ที่ถ่อม"],
      ["lion", "ลง"],
    ],
  ], lionScenes),
  ...story("เต่ากับกระต่าย", [
    [
      ["A", "ตัว"],
      ["boastful", "ที่โอ้อวด"],
      ["hare", "กระต่าย"],
      ["ridiculed", "เยาะ"],
      ["the", "เต่า"],
      ["tortoise", "ว่า"],
      ["for", "ช้า"],
      ["being", "เกิน"],
      ["slow", "ไป"],
    ],
    [
      ["Let", "มา"],
      ["us", "กัน"],
      ["settle", "ตัดสิน"],
      ["this", "เรื่อง"],
      ["with", "นี้"],
      ["a", "ด้วย"],
      ["race", "การ"],
      ["to", "แข่ง"],
      ["that", "ไป"],
      ["tree", "ต้นไม้นั้น"],
    ],
    [
      ["The", "ตัว"],
      ["hare", "กระต่าย"],
      ["surged", "พุ่ง"],
      ["ahead", "นำ"],
      ["and", "แล้ว"],
      ["decided", "คิด"],
      ["he", "ว่า"],
      ["could", "เขา"],
      ["rest", "พักได้"],
    ],
    [
      ["He", "เขา"],
      ["dozed", "งีบ"],
      ["beside", "ข้าง"],
      ["the", "ทาง"],
      ["road", "นั้น"],
      ["convinced", "มั่นใจ"],
      ["victory", "ว่า"],
      ["was", "ชนะ"],
      ["his", "แล้ว"],
    ],
    [
      ["The", "ตัว"],
      ["tortoise", "เต่า"],
      ["maintained", "รักษา"],
      ["a", "จังหวะ"],
      ["steady", "ที่สม่ำเสมอ"],
      ["pace", "ไว้"],
      ["without", "โดย"],
      ["pausing", "ไม่หยุด"],
    ],
    [
      ["She", "เธอ"],
      ["overtook", "แซง"],
      ["the", "ตัว"],
      ["hare", "กระต่าย"],
      ["while", "ขณะ"],
      ["he", "เขา"],
      ["was", "ยัง"],
      ["still", "คง"],
      ["asleep", "หลับ"],
    ],
    [
      ["The", "ตัว"],
      ["hare", "กระต่าย"],
      ["sprang", "ผุด"],
      ["up", "ลุก"],
      ["only", "ขึ้น"],
      ["to", "แต่"],
      ["find", "พบ"],
      ["he", "ว่า"],
      ["was", "ตัวเอง"],
      ["late", "มาสาย"],
    ],
    [
      ["Consistency", "ความ"],
      ["rather", "สม่ำเสมอ"],
      ["than", "ไม่ใช่"],
      ["speed", "ความเร็ว"],
      ["decided", "เป็นตัว"],
      ["the", "ตัดสิน"],
      ["race", "การแข่ง"],
      ["that", "วัน"],
      ["day", "นั้น"],
    ],
  ], hareScenes),
  ...story("เด็กหญิงผ้าคลุมแดง", [
    [
      ["A", "เด็ก"],
      ["girl", "หญิง"],
      ["in", "ใน"],
      ["a", "ผ้า"],
      ["red", "แดง"],
      ["cloak", "คลุม"],
      ["set", "ออก"],
      ["out", "เดิน"],
      ["for", "ทาง"],
      ["Grandma", "ไปหาคุณย่า"],
    ],
    [
      ["Her", "ตะกร้า"],
      ["basket", "ของเธอ"],
      ["held", "มี"],
      ["cake", "เค้ก"],
      ["and", "กับ"],
      ["fruit", "ผลไม้"],
      ["meant", "ที่ตั้งใจ"],
      ["for", "ให้"],
      ["Grandma", "คุณย่า"],
    ],
    [
      ["A", "ตัว"],
      ["scheming", "เจ้าเล่ห์"],
      ["wolf", "หมาป่า"],
      ["intercepted", "สกัด"],
      ["her", "เธอ"],
      ["along", "ระหว่าง"],
      ["the", "ทาง"],
      ["forest", "ใน"],
      ["path", "ป่า"],
    ],
    [
      ["Where", "ที่ไหน"],
      ["exactly", "กันแน่"],
      ["are", "กัน"],
      ["you", "เธอ"],
      ["heading", "กำลังไป"],
      ["this", "เช้า"],
      ["morning", "นี้"],
      ["he", "เขา"],
      ["inquired", "ถาม"],
    ],
    [
      ["I", "ฉัน"],
      ["am", "กำลัง"],
      ["bringing", "เอา"],
      ["food", "อาหาร"],
      ["to", "ไปให้"],
      ["my", "คุณ"],
      ["grandmother", "ย่า"],
      ["who", "ของฉัน"],
      ["is", "ที่"],
      ["ill", "ไม่สบาย"],
    ],
    [
      ["The", "ตัว"],
      ["wolf", "หมาป่า"],
      ["slipped", "แอบ"],
      ["ahead", "ไปก่อน"],
      ["and", "แล้ว"],
      ["reached", "ไปถึง"],
      ["the", "กระท่อม"],
      ["cottage", "นั้น"],
      ["first", "ก่อน"],
    ],
    [
      ["He", "เขา"],
      ["disguised", "ปลอม"],
      ["himself", "ตัว"],
      ["in", "ด้วย"],
      ["her", "หมวก"],
      ["cap", "ของย่า"],
      ["and", "แล้ว"],
      ["waited", "รอ"],
      ["in", "บน"],
      ["bed", "เตียง"],
    ],
    [
      ["What", "ช่าง"],
      ["strikingly", "ใหญ่"],
      ["large", "เหลือเกิน"],
      ["eyes", "ตา"],
      ["you", "ที่เธอ"],
      ["have", "มี"],
      ["the", "เด็ก"],
      ["girl", "หญิง"],
      ["observed", "เอ่ย"],
    ],
    [
      ["A", "คน"],
      ["hunter", "พราน"],
      ["overheard", "ได้ยิน"],
      ["her", "เธอ"],
      ["and", "แล้ว"],
      ["forced", "บังคับ"],
      ["the", "ตัว"],
      ["wolf", "หมาป่า"],
      ["to", "ให้"],
      ["flee", "หนีไป"],
    ],
  ], redScenes),
];

export const talesC1: Token[][] = [
  ...story("สิงโตกับหนู", [
    [
      ["A", "ตัว"],
      ["magnificent", "สง่า"],
      ["lion", "สิงโต"],
      ["dozed", "หลับ"],
      ["in", "ใน"],
      ["the", "ร่ม"],
      ["shade", "ของ"],
      ["of", "ต้น"],
      ["an", "โอ๊ก"],
      ["oak", "ต้นหนึ่ง"],
    ],
    [
      ["A", "ตัว"],
      ["trembling", "สั่น"],
      ["mouse", "หนู"],
      ["scurried", "วิ่ง"],
      ["over", "ผ่าน"],
      ["his", "อุ้ง"],
      ["outstretched", "ที่แบ"],
      ["paw", "ของเขา"],
    ],
    [
      ["Startled", "สะดุ้ง"],
      ["from", "ตื่น"],
      ["sleep", "จากหลับ"],
      ["the", "สิงโต"],
      ["lion", "จึง"],
      ["seized", "คว้า"],
      ["the", "ตัว"],
      ["tiny", "ที่"],
      ["creature", "จิ๋ว"],
    ],
    [
      ["Grant", "โปรด"],
      ["me", "ให้ฉัน"],
      ["mercy", "ซึ่งเมตตา"],
      ["and", "แล้ว"],
      ["I", "ฉัน"],
      ["may", "อาจ"],
      ["prove", "พิสูจน์"],
      ["useful", "ว่ามี"],
      ["someday", "ประโยชน์สักวัน"],
    ],
    [
      ["Amused", "ขบขัน"],
      ["rather", "มากกว่า"],
      ["than", "จะ"],
      ["angry", "โกรธ"],
      ["the", "สิงโต"],
      ["lion", "จึง"],
      ["let", "ปล่อย"],
      ["him", "เขา"],
      ["go", "ไป"],
    ],
    [
      ["Hunters", "พราน"],
      ["ensnared", "คล้อง"],
      ["the", "ตัว"],
      ["weakened", "ที่อ่อนแรง"],
      ["lion", "สิงโต"],
      ["in", "ด้วย"],
      ["a", "ตาข่าย"],
      ["heavy", "ผืน"],
      ["net", "หนัก"],
    ],
    [
      ["Hearing", "ได้ยิน"],
      ["his", "เสียง"],
      ["distress", "ทุกข์ของเขา"],
      ["the", "ตัว"],
      ["mouse", "หนู"],
      ["hurried", "จึงรีบ"],
      ["back", "กลับ"],
      ["to", "ไป"],
      ["help", "ช่วย"],
    ],
    [
      ["She", "เธอ"],
      ["severed", "กัดขาด"],
      ["the", "เส้น"],
      ["cords", "เชือก"],
      ["until", "จน"],
      ["the", "ตัว"],
      ["lion", "สิงโต"],
      ["struggled", "ดิ้น"],
      ["free", "หลุดออก"],
    ],
    [
      ["Your", "ความกล้า"],
      ["courage", "ของเธอ"],
      ["saved", "ช่วย"],
      ["me", "ฉันไว้"],
      ["said", "พูด"],
      ["the", "สิงโต"],
      ["astonished", "ที่ตะลึง"],
      ["lion", "กล่าว"],
    ],
  ], lionScenes),
  ...story("เต่ากับกระต่าย", [
    [
      ["An", "ตัว"],
      ["arrogant", "หยิ่ง"],
      ["hare", "กระต่าย"],
      ["mocked", "เยาะ"],
      ["the", "ความ"],
      ["tortoise", "อดทน"],
      ["for", "ของ"],
      ["her", "ตัว"],
      ["patience", "เต่า"],
    ],
    [
      ["Shall", "เรา"],
      ["we", "จะ"],
      ["prove", "พิสูจน์"],
      ["who", "ว่า"],
      ["is", "ใคร"],
      ["faster", "เร็วกว่า"],
      ["by", "ด้วยการ"],
      ["racing", "แข่ง"],
      ["to", "ไปยัง"],
      ["that", "ต้น"],
      ["tree", "ไม้นั้น"],
    ],
    [
      ["Confident", "มั่นใจ"],
      ["of", "ใน"],
      ["victory", "ชัย"],
      ["the", "กระต่าย"],
      ["hare", "จึง"],
      ["raced", "พุ่ง"],
      ["far", "นำ"],
      ["ahead", "ไปไกล"],
    ],
    [
      ["He", "เขา"],
      ["settled", "ลง"],
      ["down", "นอน"],
      ["for", "เพื่อ"],
      ["a", "การ"],
      ["nap", "งีบ"],
      ["beside", "ข้าง"],
      ["the", "ทาง"],
      ["road", "นั้น"],
    ],
    [
      ["The", "ตัว"],
      ["tortoise", "เต่า"],
      ["persisted", "เดิน"],
      ["and", "ต่อ"],
      ["refused", "และ"],
      ["to", "ไม่"],
      ["break", "ยอม"],
      ["stride", "ให้จังหวะสะดุด"],
    ],
    [
      ["She", "เธอ"],
      ["slipped", "แอบ"],
      ["past", "ผ่าน"],
      ["the", "ตัว"],
      ["hare", "กระต่าย"],
      ["who", "ที่"],
      ["had", "ยัง"],
      ["not", "ไม่"],
      ["yet", "ได้"],
      ["stirred", "ขยับ"],
    ],
    [
      ["The", "ตัว"],
      ["hare", "กระต่าย"],
      ["awoke", "ตื่น"],
      ["and", "แล้ว"],
      ["realized", "รู้"],
      ["the", "ว่า"],
      ["finish", "เส้น"],
      ["was", "ชัย"],
      ["taken", "ถูกยึดไปแล้ว"],
    ],
    [
      ["Steady", "ความ"],
      ["persistence", "เพียร"],
      ["outperformed", "ที่สม่ำเสมอ"],
      ["raw", "เอาชนะ"],
      ["speed", "ความเร็ว"],
      ["that", "ล้วน"],
      ["afternoon", "บ่ายนั้น"],
    ],
  ], hareScenes),
  ...story("เด็กหญิงผ้าคลุมแดง", [
    [
      ["A", "เด็ก"],
      ["girl", "หญิง"],
      ["wrapped", "ที่ห่ม"],
      ["in", "ด้วย"],
      ["a", "ผ้า"],
      ["crimson", "แดง"],
      ["cloak", "คลุม"],
      ["departed", "ออก"],
      ["for", "เดิน"],
      ["Grandma", "ทางไปหาคุณย่า"],
    ],
    [
      ["She", "เธอ"],
      ["carried", "ถือ"],
      ["freshly", "เค้ก"],
      ["baked", "ที่"],
      ["cake", "อบ"],
      ["and", "ใหม่"],
      ["fruit", "กับผลไม้"],
      ["as", "เป็น"],
      ["a", "ของ"],
      ["gift", "ขวัญ"],
    ],
    [
      ["A", "ตัว"],
      ["calculating", "ที่คำนวณ"],
      ["wolf", "หมาป่า"],
      ["waylaid", "ดัก"],
      ["her", "เธอ"],
      ["on", "บน"],
      ["the", "ทาง"],
      ["woodland", "ใน"],
      ["path", "ป่า"],
    ],
    [
      ["Where", "เธอ"],
      ["might", "กำลัง"],
      ["you", "จะ"],
      ["be", "ไป"],
      ["going", "ไหน"],
      ["on", "ใน"],
      ["this", "เช้า"],
      ["fine", "ที่"],
      ["morning", "แจ่มใส"],
    ],
    [
      ["I", "ฉัน"],
      ["am", "กำลัง"],
      ["delivering", "ส่ง"],
      ["food", "อาหาร"],
      ["to", "ไปให้"],
      ["my", "คุณ"],
      ["grandmother", "ย่า"],
      ["who", "ของฉัน"],
      ["is", "ที่"],
      ["unwell", "ไม่สบาย"],
    ],
    [
      ["The", "ตัว"],
      ["wolf", "หมาป่า"],
      ["outpaced", "ไปเร็ว"],
      ["her", "กว่า"],
      ["and", "เธอ"],
      ["slipped", "แล้ว"],
      ["into", "แอบ"],
      ["the", "เข้า"],
      ["cottage", "กระท่อม"],
    ],
    [
      ["Disguised", "ปลอม"],
      ["in", "ด้วย"],
      ["Grandma's", "หมวก"],
      ["cap", "ของคุณย่า"],
      ["he", "เขา"],
      ["lay", "นอน"],
      ["waiting", "รอ"],
      ["in", "อยู่"],
      ["bed", "บนเตียง"],
    ],
    [
      ["What", "ช่าง"],
      ["remarkably", "ใหญ่"],
      ["large", "เหลือเกิน"],
      ["eyes", "ตา"],
      ["you", "ที่เธอ"],
      ["have", "มี"],
      ["she", "เธอ"],
      ["remarked", "เอ่ย"],
      ["uneasily", "อย่างไม่สบายใจ"],
    ],
    [
      ["A", "คน"],
      ["hunter", "พราน"],
      ["nearby", "ใกล้ๆ"],
      ["intervened", "เข้ามา"],
      ["and", "แล้ว"],
      ["drove", "ไล่"],
      ["the", "ตัว"],
      ["wolf", "หมาป่า"],
      ["away", "ออกไป"],
    ],
  ], redScenes),
];

export const talesC2: Token[][] = [
  ...story("สิงโตกับหนู", [
    [
      ["A", "ตัว"],
      ["formidable", "น่าเกรงขาม"],
      ["lion", "สิงโต"],
      ["slumbered", "หลับ"],
      ["beneath", "ใต้"],
      ["the", "ต้น"],
      ["spreading", "โอ๊ก"],
      ["oak", "ที่แผ่กิ่ง"],
    ],
    [
      ["An", "ตัว"],
      ["audacious", "บังอาจ"],
      ["mouse", "หนู"],
      ["traversed", "ย่ำ"],
      ["his", "ผ่าน"],
      ["immense", "อุ้ง"],
      ["resting", "มหึมา"],
      ["paw", "ที่เขานอนทับ"],
    ],
    [
      ["The", "ตัว"],
      ["indignant", "เดือดดาล"],
      ["lion", "สิงโต"],
      ["awoke", "ตื่น"],
      ["and", "แล้ว"],
      ["clamped", "หนีบ"],
      ["the", "หนู"],
      ["mouse", "ไว้"],
      ["fast", "แน่น"],
    ],
    [
      ["Show", "โปรด"],
      ["clemency", "เมตตา"],
      ["and", "แล้ว"],
      ["I", "ฉัน"],
      ["may", "อาจ"],
      ["yet", "ยัง"],
      ["repay", "ตอบแทน"],
      ["your", "ความ"],
      ["mercy", "เมตตานั้น"],
    ],
    [
      ["The", "ตัว"],
      ["lion", "สิงโต"],
      ["relented", "ใจอ่อน"],
      ["and", "แล้ว"],
      ["released", "ปล่อย"],
      ["his", "เชลย"],
      ["unlikely", "ที่ไม่น่า"],
      ["captive", "เป็นไปได้"],
    ],
    [
      ["Hunters", "พราน"],
      ["entangled", "พันธนาการ"],
      ["the", "ตัว"],
      ["formidable", "ที่น่าเกรงขาม"],
      ["lion", "สิงโต"],
      ["in", "ด้วย"],
      ["a", "ตาข่าย"],
      ["knotted", "ที่"],
      ["net", "ผูกปม"],
    ],
    [
      ["Alerted", "ได้ยิน"],
      ["by", "จาก"],
      ["his", "เสียง"],
      ["roar", "คำรามของเขา"],
      ["the", "ตัว"],
      ["mouse", "หนู"],
      ["hastened", "จึงรีบ"],
      ["back", "กลับ"],
      ["to", "มา"],
      ["assist", "ช่วย"],
    ],
    [
      ["She", "เธอ"],
      ["frayed", "ทำให้"],
      ["the", "เชือก"],
      ["bindings", "หลุดรุ่ย"],
      ["until", "จน"],
      ["the", "ตัว"],
      ["lion", "สิงโต"],
      ["tore", "ฉีก"],
      ["free", "ตัวหลุด"],
    ],
    [
      ["I", "ฉัน"],
      ["am", "ติด"],
      ["indebted", "หนี้บุญคุณ"],
      ["to", "ต่อ"],
      ["you", "เธอ"],
      ["murmured", "กระซิบ"],
      ["the", "สิงโต"],
      ["chastened", "ที่"],
      ["lion", "สำนึก"],
    ],
  ], lionScenes),
  ...story("เต่ากับกระต่าย", [
    [
      ["A", "ตัว"],
      ["vainglorious", "หลงตัว"],
      ["hare", "กระต่าย"],
      ["derided", "ดูแคลน"],
      ["the", "เต่า"],
      ["tortoise", "ว่า"],
      ["as", "ช้า"],
      ["hopelessly", "จน"],
      ["slow", "สิ้นหวัง"],
    ],
    [
      ["He", "เขา"],
      ["proposed", "เสนอ"],
      ["a", "การ"],
      ["race", "แข่ง"],
      ["to", "ไป"],
      ["the", "ต้น"],
      ["distant", "ไม้"],
      ["tree", "ไกล"],
      ["as", "เป็น"],
      ["proof", "เครื่องพิสูจน์"],
    ],
    [
      ["Certain", "มั่นใจ"],
      ["of", "ใน"],
      ["triumph", "ชัย"],
      ["the", "กระต่าย"],
      ["hare", "จึง"],
      ["bolted", "พุ่ง"],
      ["into", "ขึ้น"],
      ["the", "นำ"],
      ["lead", "ทันที"],
    ],
    [
      ["He", "เขา"],
      ["succumbed", "จำนน"],
      ["to", "ต่อ"],
      ["drowsiness", "ความง่วง"],
      ["beside", "ข้าง"],
      ["the", "ทาง"],
      ["sunlit", "ที่"],
      ["road", "แดดส่อง"],
    ],
    [
      ["The", "ตัว"],
      ["tortoise", "เต่า"],
      ["advanced", "เดิน"],
      ["with", "หน้า"],
      ["unwavering", "ด้วย"],
      ["unbroken", "สมาธิ"],
      ["concentration", "ไม่สะดุด"],
    ],
    [
      ["She", "เธอ"],
      ["glided", "เลื้อย"],
      ["past", "ผ่าน"],
      ["the", "ตัว"],
      ["hare", "กระต่าย"],
      ["while", "ขณะ"],
      ["his", "ความ"],
      ["confidence", "มั่น"],
      ["slept", "ของเขายังหลับ"],
    ],
    [
      ["The", "ตัว"],
      ["hare", "กระต่าย"],
      ["lurched", "สะดุ้ง"],
      ["awake", "ตื่น"],
      ["and", "แล้ว"],
      ["discovered", "พบ"],
      ["he", "ว่า"],
      ["had", "ตัวเอง"],
      ["lost", "แพ้แล้ว"],
    ],
    [
      ["Unspectacular", "ความ"],
      ["persistence", "เพียร"],
      ["prevailed", "ที่ไม่ฉูดฉาด"],
      ["over", "ชนะ"],
      ["dazzling", "ความเร็ว"],
      ["careless", "ที่แวบ"],
      ["speed", "แต่ประมาท"],
    ],
  ], hareScenes),
  ...story("เด็กหญิงผ้าคลุมแดง", [
    [
      ["Cloaked", "ห่ม"],
      ["in", "ด้วย"],
      ["scarlet", "สีแดง"],
      ["the", "เด็ก"],
      ["girl", "หญิง"],
      ["ventured", "ออก"],
      ["toward", "เดิน"],
      ["Grandma's", "ทาง"],
      ["cottage", "ไปกระท่อมคุณย่า"],
    ],
    [
      ["The", "ตะกร้า"],
      ["basket", "นั้น"],
      ["contained", "มี"],
      ["cake", "เค้ก"],
      ["and", "กับ"],
      ["fruit", "ผลไม้"],
      ["intended", "ที่ตั้งใจ"],
      ["for", "ให้"],
      ["Grandma", "คุณย่า"],
    ],
    [
      ["A", "ตัว"],
      ["predatory", "นักล่า"],
      ["wolf", "หมาป่า"],
      ["accosted", "เข้าหา"],
      ["her", "เธอ"],
      ["upon", "บน"],
      ["the", "ทาง"],
      ["forest", "ใน"],
      ["path", "ป่า"],
    ],
    [
      ["Where", "ที่ไหน"],
      ["precisely", "กันแน่"],
      ["are", "กัน"],
      ["you", "เธอ"],
      ["bound", "กำลังมุ่ง"],
      ["this", "เช้า"],
      ["morning", "นี้"],
      ["he", "เขา"],
      ["asked", "ถาม"],
    ],
    [
      ["I", "ฉัน"],
      ["am", "กำลัง"],
      ["conveying", "ลำเลียง"],
      ["provisions", "เสบียง"],
      ["to", "ไปให้"],
      ["my", "คุณ"],
      ["ailing", "ย่า"],
      ["grandmother", "ที่ป่วย"],
    ],
    [
      ["The", "ตัว"],
      ["wolf", "หมาป่า"],
      ["preceded", "ล่วงหน้า"],
      ["her", "เธอไป"],
      ["and", "แล้ว"],
      ["gained", "เข้าถึง"],
      ["the", "กระท่อม"],
      ["cottage", "นั้น"],
      ["unseen", "โดยไม่มีใครเห็น"],
    ],
    [
      ["Swathed", "ห่ม"],
      ["in", "ด้วย"],
      ["her", "หมวก"],
      ["cap", "ของย่า"],
      ["he", "เขา"],
      ["reclined", "เอน"],
      ["in", "อยู่"],
      ["the", "บน"],
      ["waiting", "เตียง"],
      ["bed", "ที่รออยู่"],
    ],
    [
      ["What", "ช่าง"],
      ["prodigious", "มหึมา"],
      ["eyes", "ตา"],
      ["you", "ที่เธอ"],
      ["possess", "มี"],
      ["she", "เธอ"],
      ["observed", "เอ่ย"],
      ["warily", "อย่างระแวง"],
    ],
    [
      ["A", "คน"],
      ["hunter", "พราน"],
      ["interposed", "เข้าขวาง"],
      ["and", "แล้ว"],
      ["compelled", "บังคับ"],
      ["the", "ตัว"],
      ["wolf", "หมาป่า"],
      ["to", "ให้"],
      ["withdraw", "ถอยไป"],
    ],
  ], redScenes),
];
